// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.ogon.sdk.model;

/**
 * Protobuf type {@code pb.ApplePayPaymentDataRequest}
 */
public final class ApplePayPaymentDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.ApplePayPaymentDataRequest)
    ApplePayPaymentDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ApplePayPaymentDataRequest.newBuilder() to construct.
  private ApplePayPaymentDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ApplePayPaymentDataRequest() {
    countryCode_ = "";
    currencyCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApplePayPaymentDataRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ApplePayPaymentDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            countryCode_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            currencyCode_ = s;
            break;
          }
          case 26: {
            ru.ogon.sdk.model.ApplePayTotal.Builder subBuilder = null;
            if (total_ != null) {
              subBuilder = total_.toBuilder();
            }
            total_ = input.readMessage(ru.ogon.sdk.model.ApplePayTotal.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(total_);
              total_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.ogon.sdk.model.MobileModel.internal_static_pb_ApplePayPaymentDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.ogon.sdk.model.MobileModel.internal_static_pb_ApplePayPaymentDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.ogon.sdk.model.ApplePayPaymentDataRequest.class, ru.ogon.sdk.model.ApplePayPaymentDataRequest.Builder.class);
  }

  public static final int COUNTRY_CODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object countryCode_;
  /**
   * <code>string country_code = 1;</code>
   * @return The countryCode.
   */
  @java.lang.Override
  public java.lang.String getCountryCode() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      countryCode_ = s;
      return s;
    }
  }
  /**
   * <code>string country_code = 1;</code>
   * @return The bytes for countryCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountryCodeBytes() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      countryCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENCY_CODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object currencyCode_;
  /**
   * <code>string currency_code = 2;</code>
   * @return The currencyCode.
   */
  @java.lang.Override
  public java.lang.String getCurrencyCode() {
    java.lang.Object ref = currencyCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currencyCode_ = s;
      return s;
    }
  }
  /**
   * <code>string currency_code = 2;</code>
   * @return The bytes for currencyCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyCodeBytes() {
    java.lang.Object ref = currencyCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currencyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_FIELD_NUMBER = 3;
  private ru.ogon.sdk.model.ApplePayTotal total_;
  /**
   * <code>.pb.ApplePayTotal total = 3;</code>
   * @return Whether the total field is set.
   */
  @java.lang.Override
  public boolean hasTotal() {
    return total_ != null;
  }
  /**
   * <code>.pb.ApplePayTotal total = 3;</code>
   * @return The total.
   */
  @java.lang.Override
  public ru.ogon.sdk.model.ApplePayTotal getTotal() {
    return total_ == null ? ru.ogon.sdk.model.ApplePayTotal.getDefaultInstance() : total_;
  }
  /**
   * <code>.pb.ApplePayTotal total = 3;</code>
   */
  @java.lang.Override
  public ru.ogon.sdk.model.ApplePayTotalOrBuilder getTotalOrBuilder() {
    return getTotal();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, countryCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currencyCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currencyCode_);
    }
    if (total_ != null) {
      output.writeMessage(3, getTotal());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, countryCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currencyCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currencyCode_);
    }
    if (total_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTotal());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.ogon.sdk.model.ApplePayPaymentDataRequest)) {
      return super.equals(obj);
    }
    ru.ogon.sdk.model.ApplePayPaymentDataRequest other = (ru.ogon.sdk.model.ApplePayPaymentDataRequest) obj;

    if (!getCountryCode()
        .equals(other.getCountryCode())) return false;
    if (!getCurrencyCode()
        .equals(other.getCurrencyCode())) return false;
    if (hasTotal() != other.hasTotal()) return false;
    if (hasTotal()) {
      if (!getTotal()
          .equals(other.getTotal())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCountryCode().hashCode();
    hash = (37 * hash) + CURRENCY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrencyCode().hashCode();
    if (hasTotal()) {
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTotal().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.ogon.sdk.model.ApplePayPaymentDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.ApplePayPaymentDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.ApplePayPaymentDataRequest)
      ru.ogon.sdk.model.ApplePayPaymentDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.ogon.sdk.model.MobileModel.internal_static_pb_ApplePayPaymentDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.ogon.sdk.model.MobileModel.internal_static_pb_ApplePayPaymentDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.ogon.sdk.model.ApplePayPaymentDataRequest.class, ru.ogon.sdk.model.ApplePayPaymentDataRequest.Builder.class);
    }

    // Construct using ru.ogon.sdk.model.ApplePayPaymentDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      countryCode_ = "";

      currencyCode_ = "";

      if (totalBuilder_ == null) {
        total_ = null;
      } else {
        total_ = null;
        totalBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.ogon.sdk.model.MobileModel.internal_static_pb_ApplePayPaymentDataRequest_descriptor;
    }

    @java.lang.Override
    public ru.ogon.sdk.model.ApplePayPaymentDataRequest getDefaultInstanceForType() {
      return ru.ogon.sdk.model.ApplePayPaymentDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ru.ogon.sdk.model.ApplePayPaymentDataRequest build() {
      ru.ogon.sdk.model.ApplePayPaymentDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.ogon.sdk.model.ApplePayPaymentDataRequest buildPartial() {
      ru.ogon.sdk.model.ApplePayPaymentDataRequest result = new ru.ogon.sdk.model.ApplePayPaymentDataRequest(this);
      result.countryCode_ = countryCode_;
      result.currencyCode_ = currencyCode_;
      if (totalBuilder_ == null) {
        result.total_ = total_;
      } else {
        result.total_ = totalBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.ogon.sdk.model.ApplePayPaymentDataRequest) {
        return mergeFrom((ru.ogon.sdk.model.ApplePayPaymentDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.ogon.sdk.model.ApplePayPaymentDataRequest other) {
      if (other == ru.ogon.sdk.model.ApplePayPaymentDataRequest.getDefaultInstance()) return this;
      if (!other.getCountryCode().isEmpty()) {
        countryCode_ = other.countryCode_;
        onChanged();
      }
      if (!other.getCurrencyCode().isEmpty()) {
        currencyCode_ = other.currencyCode_;
        onChanged();
      }
      if (other.hasTotal()) {
        mergeTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.ogon.sdk.model.ApplePayPaymentDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.ogon.sdk.model.ApplePayPaymentDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object countryCode_ = "";
    /**
     * <code>string country_code = 1;</code>
     * @return The countryCode.
     */
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string country_code = 1;</code>
     * @return The bytes for countryCode.
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string country_code = 1;</code>
     * @param value The countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      countryCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountryCode() {
      
      countryCode_ = getDefaultInstance().getCountryCode();
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 1;</code>
     * @param value The bytes for countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      countryCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object currencyCode_ = "";
    /**
     * <code>string currency_code = 2;</code>
     * @return The currencyCode.
     */
    public java.lang.String getCurrencyCode() {
      java.lang.Object ref = currencyCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currency_code = 2;</code>
     * @return The bytes for currencyCode.
     */
    public com.google.protobuf.ByteString
        getCurrencyCodeBytes() {
      java.lang.Object ref = currencyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currency_code = 2;</code>
     * @param value The currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currencyCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string currency_code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrencyCode() {
      
      currencyCode_ = getDefaultInstance().getCurrencyCode();
      onChanged();
      return this;
    }
    /**
     * <code>string currency_code = 2;</code>
     * @param value The bytes for currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currencyCode_ = value;
      onChanged();
      return this;
    }

    private ru.ogon.sdk.model.ApplePayTotal total_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.ogon.sdk.model.ApplePayTotal, ru.ogon.sdk.model.ApplePayTotal.Builder, ru.ogon.sdk.model.ApplePayTotalOrBuilder> totalBuilder_;
    /**
     * <code>.pb.ApplePayTotal total = 3;</code>
     * @return Whether the total field is set.
     */
    public boolean hasTotal() {
      return totalBuilder_ != null || total_ != null;
    }
    /**
     * <code>.pb.ApplePayTotal total = 3;</code>
     * @return The total.
     */
    public ru.ogon.sdk.model.ApplePayTotal getTotal() {
      if (totalBuilder_ == null) {
        return total_ == null ? ru.ogon.sdk.model.ApplePayTotal.getDefaultInstance() : total_;
      } else {
        return totalBuilder_.getMessage();
      }
    }
    /**
     * <code>.pb.ApplePayTotal total = 3;</code>
     */
    public Builder setTotal(ru.ogon.sdk.model.ApplePayTotal value) {
      if (totalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        total_ = value;
        onChanged();
      } else {
        totalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pb.ApplePayTotal total = 3;</code>
     */
    public Builder setTotal(
        ru.ogon.sdk.model.ApplePayTotal.Builder builderForValue) {
      if (totalBuilder_ == null) {
        total_ = builderForValue.build();
        onChanged();
      } else {
        totalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pb.ApplePayTotal total = 3;</code>
     */
    public Builder mergeTotal(ru.ogon.sdk.model.ApplePayTotal value) {
      if (totalBuilder_ == null) {
        if (total_ != null) {
          total_ =
            ru.ogon.sdk.model.ApplePayTotal.newBuilder(total_).mergeFrom(value).buildPartial();
        } else {
          total_ = value;
        }
        onChanged();
      } else {
        totalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pb.ApplePayTotal total = 3;</code>
     */
    public Builder clearTotal() {
      if (totalBuilder_ == null) {
        total_ = null;
        onChanged();
      } else {
        total_ = null;
        totalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pb.ApplePayTotal total = 3;</code>
     */
    public ru.ogon.sdk.model.ApplePayTotal.Builder getTotalBuilder() {
      
      onChanged();
      return getTotalFieldBuilder().getBuilder();
    }
    /**
     * <code>.pb.ApplePayTotal total = 3;</code>
     */
    public ru.ogon.sdk.model.ApplePayTotalOrBuilder getTotalOrBuilder() {
      if (totalBuilder_ != null) {
        return totalBuilder_.getMessageOrBuilder();
      } else {
        return total_ == null ?
            ru.ogon.sdk.model.ApplePayTotal.getDefaultInstance() : total_;
      }
    }
    /**
     * <code>.pb.ApplePayTotal total = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.ogon.sdk.model.ApplePayTotal, ru.ogon.sdk.model.ApplePayTotal.Builder, ru.ogon.sdk.model.ApplePayTotalOrBuilder> 
        getTotalFieldBuilder() {
      if (totalBuilder_ == null) {
        totalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.ogon.sdk.model.ApplePayTotal, ru.ogon.sdk.model.ApplePayTotal.Builder, ru.ogon.sdk.model.ApplePayTotalOrBuilder>(
                getTotal(),
                getParentForChildren(),
                isClean());
        total_ = null;
      }
      return totalBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.ApplePayPaymentDataRequest)
  }

  // @@protoc_insertion_point(class_scope:pb.ApplePayPaymentDataRequest)
  private static final ru.ogon.sdk.model.ApplePayPaymentDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.ogon.sdk.model.ApplePayPaymentDataRequest();
  }

  public static ru.ogon.sdk.model.ApplePayPaymentDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApplePayPaymentDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<ApplePayPaymentDataRequest>() {
    @java.lang.Override
    public ApplePayPaymentDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApplePayPaymentDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApplePayPaymentDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApplePayPaymentDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.ogon.sdk.model.ApplePayPaymentDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

