// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.ogon.sdk.model;

public interface IsReadyToPayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.IsReadyToPayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 api_version = 1;</code>
   * @return The apiVersion.
   */
  int getApiVersion();

  /**
   * <code>uint32 api_version_minor = 2;</code>
   * @return The apiVersionMinor.
   */
  int getApiVersionMinor();

  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 3;</code>
   */
  java.util.List<ru.ogon.sdk.model.PaymentMethodSpecification> 
      getAllowedPaymentMethodsList();
  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 3;</code>
   */
  ru.ogon.sdk.model.PaymentMethodSpecification getAllowedPaymentMethods(int index);
  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 3;</code>
   */
  int getAllowedPaymentMethodsCount();
  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 3;</code>
   */
  java.util.List<? extends ru.ogon.sdk.model.PaymentMethodSpecificationOrBuilder> 
      getAllowedPaymentMethodsOrBuilderList();
  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 3;</code>
   */
  ru.ogon.sdk.model.PaymentMethodSpecificationOrBuilder getAllowedPaymentMethodsOrBuilder(
      int index);

  /**
   * <code>bool existing_payment_method_required = 4;</code>
   * @return The existingPaymentMethodRequired.
   */
  boolean getExistingPaymentMethodRequired();
}
