// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.ogon.sdk.model;

/**
 * Protobuf type {@code pb.MobileAnalyticsEvent}
 */
public final class MobileAnalyticsEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.MobileAnalyticsEvent)
    MobileAnalyticsEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MobileAnalyticsEvent.newBuilder() to construct.
  private MobileAnalyticsEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MobileAnalyticsEvent() {
    eventType_ = 0;
    value_ = "";
    utmMedium_ = "";
    utmSource_ = "";
    utmCampaign_ = "";
    utmTerm_ = "";
    utmContent_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MobileAnalyticsEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MobileAnalyticsEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            eventType_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            value_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            utmMedium_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            utmSource_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            utmCampaign_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            utmTerm_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            utmContent_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.ogon.sdk.model.MobileModel.internal_static_pb_MobileAnalyticsEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.ogon.sdk.model.MobileModel.internal_static_pb_MobileAnalyticsEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.ogon.sdk.model.MobileAnalyticsEvent.class, ru.ogon.sdk.model.MobileAnalyticsEvent.Builder.class);
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 1;
  private int eventType_;
  /**
   * <code>.pb.MobileAnalyticsEventType event_type = 1;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  @java.lang.Override public int getEventTypeValue() {
    return eventType_;
  }
  /**
   * <code>.pb.MobileAnalyticsEventType event_type = 1;</code>
   * @return The eventType.
   */
  @java.lang.Override public ru.ogon.sdk.model.MobileAnalyticsEventType getEventType() {
    @SuppressWarnings("deprecation")
    ru.ogon.sdk.model.MobileAnalyticsEventType result = ru.ogon.sdk.model.MobileAnalyticsEventType.valueOf(eventType_);
    return result == null ? ru.ogon.sdk.model.MobileAnalyticsEventType.UNRECOGNIZED : result;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private volatile java.lang.Object value_;
  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UTM_MEDIUM_FIELD_NUMBER = 3;
  private volatile java.lang.Object utmMedium_;
  /**
   * <code>string utm_medium = 3;</code>
   * @return The utmMedium.
   */
  @java.lang.Override
  public java.lang.String getUtmMedium() {
    java.lang.Object ref = utmMedium_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      utmMedium_ = s;
      return s;
    }
  }
  /**
   * <code>string utm_medium = 3;</code>
   * @return The bytes for utmMedium.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUtmMediumBytes() {
    java.lang.Object ref = utmMedium_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      utmMedium_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UTM_SOURCE_FIELD_NUMBER = 4;
  private volatile java.lang.Object utmSource_;
  /**
   * <code>string utm_source = 4;</code>
   * @return The utmSource.
   */
  @java.lang.Override
  public java.lang.String getUtmSource() {
    java.lang.Object ref = utmSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      utmSource_ = s;
      return s;
    }
  }
  /**
   * <code>string utm_source = 4;</code>
   * @return The bytes for utmSource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUtmSourceBytes() {
    java.lang.Object ref = utmSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      utmSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UTM_CAMPAIGN_FIELD_NUMBER = 5;
  private volatile java.lang.Object utmCampaign_;
  /**
   * <code>string utm_campaign = 5;</code>
   * @return The utmCampaign.
   */
  @java.lang.Override
  public java.lang.String getUtmCampaign() {
    java.lang.Object ref = utmCampaign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      utmCampaign_ = s;
      return s;
    }
  }
  /**
   * <code>string utm_campaign = 5;</code>
   * @return The bytes for utmCampaign.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUtmCampaignBytes() {
    java.lang.Object ref = utmCampaign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      utmCampaign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UTM_TERM_FIELD_NUMBER = 6;
  private volatile java.lang.Object utmTerm_;
  /**
   * <code>string utm_term = 6;</code>
   * @return The utmTerm.
   */
  @java.lang.Override
  public java.lang.String getUtmTerm() {
    java.lang.Object ref = utmTerm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      utmTerm_ = s;
      return s;
    }
  }
  /**
   * <code>string utm_term = 6;</code>
   * @return The bytes for utmTerm.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUtmTermBytes() {
    java.lang.Object ref = utmTerm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      utmTerm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UTM_CONTENT_FIELD_NUMBER = 7;
  private volatile java.lang.Object utmContent_;
  /**
   * <code>string utm_content = 7;</code>
   * @return The utmContent.
   */
  @java.lang.Override
  public java.lang.String getUtmContent() {
    java.lang.Object ref = utmContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      utmContent_ = s;
      return s;
    }
  }
  /**
   * <code>string utm_content = 7;</code>
   * @return The bytes for utmContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUtmContentBytes() {
    java.lang.Object ref = utmContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      utmContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventType_ != ru.ogon.sdk.model.MobileAnalyticsEventType.MOBILE_ANALYTICS_EVENT_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, eventType_);
    }
    if (!getValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
    }
    if (!getUtmMediumBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, utmMedium_);
    }
    if (!getUtmSourceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, utmSource_);
    }
    if (!getUtmCampaignBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, utmCampaign_);
    }
    if (!getUtmTermBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, utmTerm_);
    }
    if (!getUtmContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, utmContent_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventType_ != ru.ogon.sdk.model.MobileAnalyticsEventType.MOBILE_ANALYTICS_EVENT_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, eventType_);
    }
    if (!getValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
    }
    if (!getUtmMediumBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, utmMedium_);
    }
    if (!getUtmSourceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, utmSource_);
    }
    if (!getUtmCampaignBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, utmCampaign_);
    }
    if (!getUtmTermBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, utmTerm_);
    }
    if (!getUtmContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, utmContent_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.ogon.sdk.model.MobileAnalyticsEvent)) {
      return super.equals(obj);
    }
    ru.ogon.sdk.model.MobileAnalyticsEvent other = (ru.ogon.sdk.model.MobileAnalyticsEvent) obj;

    if (eventType_ != other.eventType_) return false;
    if (!getValue()
        .equals(other.getValue())) return false;
    if (!getUtmMedium()
        .equals(other.getUtmMedium())) return false;
    if (!getUtmSource()
        .equals(other.getUtmSource())) return false;
    if (!getUtmCampaign()
        .equals(other.getUtmCampaign())) return false;
    if (!getUtmTerm()
        .equals(other.getUtmTerm())) return false;
    if (!getUtmContent()
        .equals(other.getUtmContent())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + eventType_;
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (37 * hash) + UTM_MEDIUM_FIELD_NUMBER;
    hash = (53 * hash) + getUtmMedium().hashCode();
    hash = (37 * hash) + UTM_SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getUtmSource().hashCode();
    hash = (37 * hash) + UTM_CAMPAIGN_FIELD_NUMBER;
    hash = (53 * hash) + getUtmCampaign().hashCode();
    hash = (37 * hash) + UTM_TERM_FIELD_NUMBER;
    hash = (53 * hash) + getUtmTerm().hashCode();
    hash = (37 * hash) + UTM_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getUtmContent().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ogon.sdk.model.MobileAnalyticsEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.ogon.sdk.model.MobileAnalyticsEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.MobileAnalyticsEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.MobileAnalyticsEvent)
      ru.ogon.sdk.model.MobileAnalyticsEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.ogon.sdk.model.MobileModel.internal_static_pb_MobileAnalyticsEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.ogon.sdk.model.MobileModel.internal_static_pb_MobileAnalyticsEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.ogon.sdk.model.MobileAnalyticsEvent.class, ru.ogon.sdk.model.MobileAnalyticsEvent.Builder.class);
    }

    // Construct using ru.ogon.sdk.model.MobileAnalyticsEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      eventType_ = 0;

      value_ = "";

      utmMedium_ = "";

      utmSource_ = "";

      utmCampaign_ = "";

      utmTerm_ = "";

      utmContent_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.ogon.sdk.model.MobileModel.internal_static_pb_MobileAnalyticsEvent_descriptor;
    }

    @java.lang.Override
    public ru.ogon.sdk.model.MobileAnalyticsEvent getDefaultInstanceForType() {
      return ru.ogon.sdk.model.MobileAnalyticsEvent.getDefaultInstance();
    }

    @java.lang.Override
    public ru.ogon.sdk.model.MobileAnalyticsEvent build() {
      ru.ogon.sdk.model.MobileAnalyticsEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.ogon.sdk.model.MobileAnalyticsEvent buildPartial() {
      ru.ogon.sdk.model.MobileAnalyticsEvent result = new ru.ogon.sdk.model.MobileAnalyticsEvent(this);
      result.eventType_ = eventType_;
      result.value_ = value_;
      result.utmMedium_ = utmMedium_;
      result.utmSource_ = utmSource_;
      result.utmCampaign_ = utmCampaign_;
      result.utmTerm_ = utmTerm_;
      result.utmContent_ = utmContent_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.ogon.sdk.model.MobileAnalyticsEvent) {
        return mergeFrom((ru.ogon.sdk.model.MobileAnalyticsEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.ogon.sdk.model.MobileAnalyticsEvent other) {
      if (other == ru.ogon.sdk.model.MobileAnalyticsEvent.getDefaultInstance()) return this;
      if (other.eventType_ != 0) {
        setEventTypeValue(other.getEventTypeValue());
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      if (!other.getUtmMedium().isEmpty()) {
        utmMedium_ = other.utmMedium_;
        onChanged();
      }
      if (!other.getUtmSource().isEmpty()) {
        utmSource_ = other.utmSource_;
        onChanged();
      }
      if (!other.getUtmCampaign().isEmpty()) {
        utmCampaign_ = other.utmCampaign_;
        onChanged();
      }
      if (!other.getUtmTerm().isEmpty()) {
        utmTerm_ = other.utmTerm_;
        onChanged();
      }
      if (!other.getUtmContent().isEmpty()) {
        utmContent_ = other.utmContent_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.ogon.sdk.model.MobileAnalyticsEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.ogon.sdk.model.MobileAnalyticsEvent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int eventType_ = 0;
    /**
     * <code>.pb.MobileAnalyticsEventType event_type = 1;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>.pb.MobileAnalyticsEventType event_type = 1;</code>
     * @param value The enum numeric value on the wire for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeValue(int value) {
      
      eventType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pb.MobileAnalyticsEventType event_type = 1;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public ru.ogon.sdk.model.MobileAnalyticsEventType getEventType() {
      @SuppressWarnings("deprecation")
      ru.ogon.sdk.model.MobileAnalyticsEventType result = ru.ogon.sdk.model.MobileAnalyticsEventType.valueOf(eventType_);
      return result == null ? ru.ogon.sdk.model.MobileAnalyticsEventType.UNRECOGNIZED : result;
    }
    /**
     * <code>.pb.MobileAnalyticsEventType event_type = 1;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(ru.ogon.sdk.model.MobileAnalyticsEventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      eventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pb.MobileAnalyticsEventType event_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      
      eventType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <code>string value = 2;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object utmMedium_ = "";
    /**
     * <code>string utm_medium = 3;</code>
     * @return The utmMedium.
     */
    public java.lang.String getUtmMedium() {
      java.lang.Object ref = utmMedium_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        utmMedium_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string utm_medium = 3;</code>
     * @return The bytes for utmMedium.
     */
    public com.google.protobuf.ByteString
        getUtmMediumBytes() {
      java.lang.Object ref = utmMedium_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        utmMedium_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string utm_medium = 3;</code>
     * @param value The utmMedium to set.
     * @return This builder for chaining.
     */
    public Builder setUtmMedium(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      utmMedium_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string utm_medium = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtmMedium() {
      
      utmMedium_ = getDefaultInstance().getUtmMedium();
      onChanged();
      return this;
    }
    /**
     * <code>string utm_medium = 3;</code>
     * @param value The bytes for utmMedium to set.
     * @return This builder for chaining.
     */
    public Builder setUtmMediumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      utmMedium_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object utmSource_ = "";
    /**
     * <code>string utm_source = 4;</code>
     * @return The utmSource.
     */
    public java.lang.String getUtmSource() {
      java.lang.Object ref = utmSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        utmSource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string utm_source = 4;</code>
     * @return The bytes for utmSource.
     */
    public com.google.protobuf.ByteString
        getUtmSourceBytes() {
      java.lang.Object ref = utmSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        utmSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string utm_source = 4;</code>
     * @param value The utmSource to set.
     * @return This builder for chaining.
     */
    public Builder setUtmSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      utmSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string utm_source = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtmSource() {
      
      utmSource_ = getDefaultInstance().getUtmSource();
      onChanged();
      return this;
    }
    /**
     * <code>string utm_source = 4;</code>
     * @param value The bytes for utmSource to set.
     * @return This builder for chaining.
     */
    public Builder setUtmSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      utmSource_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object utmCampaign_ = "";
    /**
     * <code>string utm_campaign = 5;</code>
     * @return The utmCampaign.
     */
    public java.lang.String getUtmCampaign() {
      java.lang.Object ref = utmCampaign_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        utmCampaign_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string utm_campaign = 5;</code>
     * @return The bytes for utmCampaign.
     */
    public com.google.protobuf.ByteString
        getUtmCampaignBytes() {
      java.lang.Object ref = utmCampaign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        utmCampaign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string utm_campaign = 5;</code>
     * @param value The utmCampaign to set.
     * @return This builder for chaining.
     */
    public Builder setUtmCampaign(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      utmCampaign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string utm_campaign = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtmCampaign() {
      
      utmCampaign_ = getDefaultInstance().getUtmCampaign();
      onChanged();
      return this;
    }
    /**
     * <code>string utm_campaign = 5;</code>
     * @param value The bytes for utmCampaign to set.
     * @return This builder for chaining.
     */
    public Builder setUtmCampaignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      utmCampaign_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object utmTerm_ = "";
    /**
     * <code>string utm_term = 6;</code>
     * @return The utmTerm.
     */
    public java.lang.String getUtmTerm() {
      java.lang.Object ref = utmTerm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        utmTerm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string utm_term = 6;</code>
     * @return The bytes for utmTerm.
     */
    public com.google.protobuf.ByteString
        getUtmTermBytes() {
      java.lang.Object ref = utmTerm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        utmTerm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string utm_term = 6;</code>
     * @param value The utmTerm to set.
     * @return This builder for chaining.
     */
    public Builder setUtmTerm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      utmTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string utm_term = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtmTerm() {
      
      utmTerm_ = getDefaultInstance().getUtmTerm();
      onChanged();
      return this;
    }
    /**
     * <code>string utm_term = 6;</code>
     * @param value The bytes for utmTerm to set.
     * @return This builder for chaining.
     */
    public Builder setUtmTermBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      utmTerm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object utmContent_ = "";
    /**
     * <code>string utm_content = 7;</code>
     * @return The utmContent.
     */
    public java.lang.String getUtmContent() {
      java.lang.Object ref = utmContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        utmContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string utm_content = 7;</code>
     * @return The bytes for utmContent.
     */
    public com.google.protobuf.ByteString
        getUtmContentBytes() {
      java.lang.Object ref = utmContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        utmContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string utm_content = 7;</code>
     * @param value The utmContent to set.
     * @return This builder for chaining.
     */
    public Builder setUtmContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      utmContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string utm_content = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtmContent() {
      
      utmContent_ = getDefaultInstance().getUtmContent();
      onChanged();
      return this;
    }
    /**
     * <code>string utm_content = 7;</code>
     * @param value The bytes for utmContent to set.
     * @return This builder for chaining.
     */
    public Builder setUtmContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      utmContent_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.MobileAnalyticsEvent)
  }

  // @@protoc_insertion_point(class_scope:pb.MobileAnalyticsEvent)
  private static final ru.ogon.sdk.model.MobileAnalyticsEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.ogon.sdk.model.MobileAnalyticsEvent();
  }

  public static ru.ogon.sdk.model.MobileAnalyticsEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MobileAnalyticsEvent>
      PARSER = new com.google.protobuf.AbstractParser<MobileAnalyticsEvent>() {
    @java.lang.Override
    public MobileAnalyticsEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MobileAnalyticsEvent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MobileAnalyticsEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MobileAnalyticsEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.ogon.sdk.model.MobileAnalyticsEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

