// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.ogon.sdk.model;

/**
 * Protobuf enum {@code pb.MobileAnalyticsEventType}
 */
public enum MobileAnalyticsEventType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MOBILE_ANALYTICS_EVENT_TYPE_UNSPECIFIED = 0;</code>
   */
  MOBILE_ANALYTICS_EVENT_TYPE_UNSPECIFIED(0),
  /**
   * <code>MOBILE_ANALYTICS_EVENT_TYPE_ANDROID_APP_INSTALL_REFERRER = 1;</code>
   */
  MOBILE_ANALYTICS_EVENT_TYPE_ANDROID_APP_INSTALL_REFERRER(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MOBILE_ANALYTICS_EVENT_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int MOBILE_ANALYTICS_EVENT_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>MOBILE_ANALYTICS_EVENT_TYPE_ANDROID_APP_INSTALL_REFERRER = 1;</code>
   */
  public static final int MOBILE_ANALYTICS_EVENT_TYPE_ANDROID_APP_INSTALL_REFERRER_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MobileAnalyticsEventType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MobileAnalyticsEventType forNumber(int value) {
    switch (value) {
      case 0: return MOBILE_ANALYTICS_EVENT_TYPE_UNSPECIFIED;
      case 1: return MOBILE_ANALYTICS_EVENT_TYPE_ANDROID_APP_INSTALL_REFERRER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MobileAnalyticsEventType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MobileAnalyticsEventType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MobileAnalyticsEventType>() {
          public MobileAnalyticsEventType findValueByNumber(int number) {
            return MobileAnalyticsEventType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ru.ogon.sdk.model.MobileModel.getDescriptor().getEnumTypes().get(1);
  }

  private static final MobileAnalyticsEventType[] VALUES = values();

  public static MobileAnalyticsEventType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MobileAnalyticsEventType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pb.MobileAnalyticsEventType)
}

