// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

public interface ApplePayPaymentDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.ApplePayPaymentData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pb.ApplePayPaymentToken token = 1;</code>
   * @return Whether the token field is set.
   */
  boolean hasToken();
  /**
   * <code>.pb.ApplePayPaymentToken token = 1;</code>
   * @return The token.
   */
  ApplePayPaymentToken getToken();
  /**
   * <code>.pb.ApplePayPaymentToken token = 1;</code>
   */
  ApplePayPaymentTokenOrBuilder getTokenOrBuilder();
}
