// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

/**
 * Protobuf type {@code pb.CardInfo}
 */
public final class CardInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.CardInfo)
    CardInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CardInfo.newBuilder() to construct.
  private CardInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CardInfo() {
    cardNetwork_ = "";
    cardDetails_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CardInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CardInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            cardNetwork_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            cardDetails_ = s;
            break;
          }
          case 26: {
            Address.Builder subBuilder = null;
            if (billingAddress_ != null) {
              subBuilder = billingAddress_.toBuilder();
            }
            billingAddress_ = input.readMessage(Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(billingAddress_);
              billingAddress_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MobileModel.internal_static_pb_CardInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MobileModel.internal_static_pb_CardInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CardInfo.class, Builder.class);
  }

  public static final int CARD_NETWORK_FIELD_NUMBER = 1;
  private volatile Object cardNetwork_;
  /**
   * <code>string card_network = 1;</code>
   * @return The cardNetwork.
   */
  @Override
  public String getCardNetwork() {
    Object ref = cardNetwork_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cardNetwork_ = s;
      return s;
    }
  }
  /**
   * <code>string card_network = 1;</code>
   * @return The bytes for cardNetwork.
   */
  @Override
  public com.google.protobuf.ByteString
      getCardNetworkBytes() {
    Object ref = cardNetwork_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cardNetwork_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARD_DETAILS_FIELD_NUMBER = 2;
  private volatile Object cardDetails_;
  /**
   * <code>string card_details = 2;</code>
   * @return The cardDetails.
   */
  @Override
  public String getCardDetails() {
    Object ref = cardDetails_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cardDetails_ = s;
      return s;
    }
  }
  /**
   * <code>string card_details = 2;</code>
   * @return The bytes for cardDetails.
   */
  @Override
  public com.google.protobuf.ByteString
      getCardDetailsBytes() {
    Object ref = cardDetails_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cardDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BILLING_ADDRESS_FIELD_NUMBER = 3;
  private Address billingAddress_;
  /**
   * <code>.pb.Address billing_address = 3;</code>
   * @return Whether the billingAddress field is set.
   */
  @Override
  public boolean hasBillingAddress() {
    return billingAddress_ != null;
  }
  /**
   * <code>.pb.Address billing_address = 3;</code>
   * @return The billingAddress.
   */
  @Override
  public Address getBillingAddress() {
    return billingAddress_ == null ? Address.getDefaultInstance() : billingAddress_;
  }
  /**
   * <code>.pb.Address billing_address = 3;</code>
   */
  @Override
  public AddressOrBuilder getBillingAddressOrBuilder() {
    return getBillingAddress();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCardNetworkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cardNetwork_);
    }
    if (!getCardDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cardDetails_);
    }
    if (billingAddress_ != null) {
      output.writeMessage(3, getBillingAddress());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCardNetworkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cardNetwork_);
    }
    if (!getCardDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cardDetails_);
    }
    if (billingAddress_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBillingAddress());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CardInfo)) {
      return super.equals(obj);
    }
    CardInfo other = (CardInfo) obj;

    if (!getCardNetwork()
        .equals(other.getCardNetwork())) return false;
    if (!getCardDetails()
        .equals(other.getCardDetails())) return false;
    if (hasBillingAddress() != other.hasBillingAddress()) return false;
    if (hasBillingAddress()) {
      if (!getBillingAddress()
          .equals(other.getBillingAddress())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARD_NETWORK_FIELD_NUMBER;
    hash = (53 * hash) + getCardNetwork().hashCode();
    hash = (37 * hash) + CARD_DETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getCardDetails().hashCode();
    if (hasBillingAddress()) {
      hash = (37 * hash) + BILLING_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getBillingAddress().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CardInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CardInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CardInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CardInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CardInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CardInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CardInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CardInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CardInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CardInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CardInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CardInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CardInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.CardInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.CardInfo)
      CardInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MobileModel.internal_static_pb_CardInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MobileModel.internal_static_pb_CardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CardInfo.class, Builder.class);
    }

    // Construct using ru.pnhub.widgetsdk.model.CardInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      cardNetwork_ = "";

      cardDetails_ = "";

      if (billingAddressBuilder_ == null) {
        billingAddress_ = null;
      } else {
        billingAddress_ = null;
        billingAddressBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MobileModel.internal_static_pb_CardInfo_descriptor;
    }

    @Override
    public CardInfo getDefaultInstanceForType() {
      return CardInfo.getDefaultInstance();
    }

    @Override
    public CardInfo build() {
      CardInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CardInfo buildPartial() {
      CardInfo result = new CardInfo(this);
      result.cardNetwork_ = cardNetwork_;
      result.cardDetails_ = cardDetails_;
      if (billingAddressBuilder_ == null) {
        result.billingAddress_ = billingAddress_;
      } else {
        result.billingAddress_ = billingAddressBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CardInfo) {
        return mergeFrom((CardInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CardInfo other) {
      if (other == CardInfo.getDefaultInstance()) return this;
      if (!other.getCardNetwork().isEmpty()) {
        cardNetwork_ = other.cardNetwork_;
        onChanged();
      }
      if (!other.getCardDetails().isEmpty()) {
        cardDetails_ = other.cardDetails_;
        onChanged();
      }
      if (other.hasBillingAddress()) {
        mergeBillingAddress(other.getBillingAddress());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CardInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CardInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object cardNetwork_ = "";
    /**
     * <code>string card_network = 1;</code>
     * @return The cardNetwork.
     */
    public String getCardNetwork() {
      Object ref = cardNetwork_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cardNetwork_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string card_network = 1;</code>
     * @return The bytes for cardNetwork.
     */
    public com.google.protobuf.ByteString
        getCardNetworkBytes() {
      Object ref = cardNetwork_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cardNetwork_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string card_network = 1;</code>
     * @param value The cardNetwork to set.
     * @return This builder for chaining.
     */
    public Builder setCardNetwork(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardNetwork_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string card_network = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCardNetwork() {
      
      cardNetwork_ = getDefaultInstance().getCardNetwork();
      onChanged();
      return this;
    }
    /**
     * <code>string card_network = 1;</code>
     * @param value The bytes for cardNetwork to set.
     * @return This builder for chaining.
     */
    public Builder setCardNetworkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardNetwork_ = value;
      onChanged();
      return this;
    }

    private Object cardDetails_ = "";
    /**
     * <code>string card_details = 2;</code>
     * @return The cardDetails.
     */
    public String getCardDetails() {
      Object ref = cardDetails_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cardDetails_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string card_details = 2;</code>
     * @return The bytes for cardDetails.
     */
    public com.google.protobuf.ByteString
        getCardDetailsBytes() {
      Object ref = cardDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cardDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string card_details = 2;</code>
     * @param value The cardDetails to set.
     * @return This builder for chaining.
     */
    public Builder setCardDetails(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string card_details = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCardDetails() {
      
      cardDetails_ = getDefaultInstance().getCardDetails();
      onChanged();
      return this;
    }
    /**
     * <code>string card_details = 2;</code>
     * @param value The bytes for cardDetails to set.
     * @return This builder for chaining.
     */
    public Builder setCardDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardDetails_ = value;
      onChanged();
      return this;
    }

    private Address billingAddress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Address, Address.Builder, AddressOrBuilder> billingAddressBuilder_;
    /**
     * <code>.pb.Address billing_address = 3;</code>
     * @return Whether the billingAddress field is set.
     */
    public boolean hasBillingAddress() {
      return billingAddressBuilder_ != null || billingAddress_ != null;
    }
    /**
     * <code>.pb.Address billing_address = 3;</code>
     * @return The billingAddress.
     */
    public Address getBillingAddress() {
      if (billingAddressBuilder_ == null) {
        return billingAddress_ == null ? Address.getDefaultInstance() : billingAddress_;
      } else {
        return billingAddressBuilder_.getMessage();
      }
    }
    /**
     * <code>.pb.Address billing_address = 3;</code>
     */
    public Builder setBillingAddress(Address value) {
      if (billingAddressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        billingAddress_ = value;
        onChanged();
      } else {
        billingAddressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pb.Address billing_address = 3;</code>
     */
    public Builder setBillingAddress(
        Address.Builder builderForValue) {
      if (billingAddressBuilder_ == null) {
        billingAddress_ = builderForValue.build();
        onChanged();
      } else {
        billingAddressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pb.Address billing_address = 3;</code>
     */
    public Builder mergeBillingAddress(Address value) {
      if (billingAddressBuilder_ == null) {
        if (billingAddress_ != null) {
          billingAddress_ =
            Address.newBuilder(billingAddress_).mergeFrom(value).buildPartial();
        } else {
          billingAddress_ = value;
        }
        onChanged();
      } else {
        billingAddressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pb.Address billing_address = 3;</code>
     */
    public Builder clearBillingAddress() {
      if (billingAddressBuilder_ == null) {
        billingAddress_ = null;
        onChanged();
      } else {
        billingAddress_ = null;
        billingAddressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pb.Address billing_address = 3;</code>
     */
    public Address.Builder getBillingAddressBuilder() {
      
      onChanged();
      return getBillingAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.pb.Address billing_address = 3;</code>
     */
    public AddressOrBuilder getBillingAddressOrBuilder() {
      if (billingAddressBuilder_ != null) {
        return billingAddressBuilder_.getMessageOrBuilder();
      } else {
        return billingAddress_ == null ?
            Address.getDefaultInstance() : billingAddress_;
      }
    }
    /**
     * <code>.pb.Address billing_address = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Address, Address.Builder, AddressOrBuilder>
        getBillingAddressFieldBuilder() {
      if (billingAddressBuilder_ == null) {
        billingAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Address, Address.Builder, AddressOrBuilder>(
                getBillingAddress(),
                getParentForChildren(),
                isClean());
        billingAddress_ = null;
      }
      return billingAddressBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.CardInfo)
  }

  // @@protoc_insertion_point(class_scope:pb.CardInfo)
  private static final CardInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CardInfo();
  }

  public static CardInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CardInfo>
      PARSER = new com.google.protobuf.AbstractParser<CardInfo>() {
    @Override
    public CardInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CardInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CardInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CardInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public CardInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

