// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

public interface DisplayItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.DisplayItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string label = 1;</code>
   * @return The label.
   */
  String getLabel();
  /**
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string price = 3;</code>
   * @return The price.
   */
  String getPrice();
  /**
   * <code>string price = 3;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  String getStatus();
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
