// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

public interface MerchantInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.MerchantInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string merchant_id = 1;</code>
   * @return The merchantId.
   */
  java.lang.String getMerchantId();
  /**
   * <code>string merchant_id = 1;</code>
   * @return The bytes for merchantId.
   */
  com.google.protobuf.ByteString
      getMerchantIdBytes();

  /**
   * <code>string merchant_name = 2;</code>
   * @return The merchantName.
   */
  java.lang.String getMerchantName();
  /**
   * <code>string merchant_name = 2;</code>
   * @return The bytes for merchantName.
   */
  com.google.protobuf.ByteString
      getMerchantNameBytes();
}
