// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

public final class MobileModel {
  private MobileModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_MobileEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_MobileEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_IsReadyToPayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_IsReadyToPayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PaymentDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PaymentDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_MerchantInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_MerchantInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ShippingAddressParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ShippingAddressParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_TransactionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_TransactionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_DisplayItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_DisplayItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ShippingOptionParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ShippingOptionParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ShippingOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ShippingOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PaymentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PaymentData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SelectionOptionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SelectionOptionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PaymentMethodData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PaymentMethodData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_CardInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_CardInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PaymentMethodTokenizationData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PaymentMethodTokenizationData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PaymentMethodSpecification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PaymentMethodSpecification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_CardParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_CardParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_TokenizationSpecification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_TokenizationSpecification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_TokenizationSpecification_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_TokenizationSpecification_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_BillingAddressParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_BillingAddressParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_CardNetworkParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_CardNetworkParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_MobileError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_MobileError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ApplePayPaymentDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ApplePayPaymentDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ApplePayTotal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ApplePayTotal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ApplePayPaymentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ApplePayPaymentData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ApplePayPaymentToken_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ApplePayPaymentToken_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ApplePaymentMethod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ApplePaymentMethod_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032pb/apis/mobile.model.proto\022\002pb\"\321\003\n\013Mob" +
      "ileEvent\022!\n\004type\030\001 \001(\0162\023.pb.MobileEventT" +
      "ype\022 \n\005error\030\002 \001(\0132\017.pb.MobileErrorH\000\022:\n" +
      "\027is_ready_to_pay_request\030\003 \001(\0132\027.pb.IsRe" +
      "adyToPayRequestH\000\0226\n\024payment_data_reques" +
      "t\030\004 \001(\0132\026.pb.PaymentDataRequestH\000\022\031\n\017is_" +
      "ready_to_pay\030\005 \001(\010H\000\022\'\n\014payment_data\030\006 \001" +
      "(\0132\017.pb.PaymentDataH\000\022G\n\035applepay_paymen" +
      "t_data_request\030\007 \001(\0132\036.pb.ApplePayPaymen" +
      "tDataRequestH\000\0228\n\025applepay_payment_data\030" +
      "\010 \001(\0132\027.pb.ApplePayPaymentDataH\000\022\032\n\020open" +
      "_url_request\030\t \001(\tH\000\022\033\n\021share_url_reques" +
      "t\030\n \001(\tH\000B\t\n\007payload\"\260\001\n\023IsReadyToPayReq" +
      "uest\022\023\n\013api_version\030\001 \001(\r\022\031\n\021api_version" +
      "_minor\030\002 \001(\r\022?\n\027allowed_payment_methods\030" +
      "\003 \003(\0132\036.pb.PaymentMethodSpecification\022(\n" +
      " existing_payment_method_required\030\004 \001(\010\"" +
      "\300\003\n\022PaymentDataRequest\022\'\n\rmerchant_info\030" +
      "\001 \001(\0132\020.pb.MerchantInfo\022\023\n\013api_version\030\002" +
      " \001(\r\022\031\n\021api_version_minor\030\003 \001(\r\022\026\n\016email" +
      "_required\030\004 \001(\010\022!\n\031shipping_address_requ" +
      "ired\030\005 \001(\010\022B\n\033shipping_address_parameter" +
      "s\030\006 \001(\0132\035.pb.ShippingAddressParameters\022?" +
      "\n\027allowed_payment_methods\030\007 \003(\0132\036.pb.Pay" +
      "mentMethodSpecification\022-\n\020transaction_i" +
      "nfo\030\010 \001(\0132\023.pb.TransactionInfo\022 \n\030shippi" +
      "ng_option_required\030\t \001(\010\022@\n\032shipping_opt" +
      "ion_parameters\030\n \001(\0132\034.pb.ShippingOption" +
      "Parameters\":\n\014MerchantInfo\022\023\n\013merchant_i" +
      "d\030\001 \001(\t\022\025\n\rmerchant_name\030\002 \001(\t\"Y\n\031Shippi" +
      "ngAddressParameters\022\035\n\025allowed_country_c" +
      "odes\030\001 \003(\t\022\035\n\025phone_number_required\030\002 \001(" +
      "\010\"\375\001\n\017TransactionInfo\022\026\n\016transaction_id\030" +
      "\001 \001(\t\022\025\n\rcurrency_code\030\002 \001(\t\022\024\n\014country_" +
      "code\030\003 \001(\t\022\023\n\013total_price\030\004 \001(\t\022\031\n\021total" +
      "_price_label\030\005 \001(\t\022\032\n\022total_price_status" +
      "\030\006 \001(\t\022\030\n\020transaction_note\030\007 \001(\t\022\027\n\017chec" +
      "kout_option\030\010 \001(\t\022&\n\rdisplay_items\030\t \003(\013" +
      "2\017.pb.DisplayItem\"I\n\013DisplayItem\022\r\n\005labe" +
      "l\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\r\n\005price\030\003 \001(\t\022\016\n\006" +
      "status\030\004 \001(\t\"l\n\030ShippingOptionParameters" +
      "\022,\n\020shipping_options\030\001 \003(\0132\022.pb.Shipping" +
      "Option\022\"\n\032default_selected_option_id\030\002 \001" +
      "(\t\"@\n\016ShippingOption\022\n\n\002id\030\001 \001(\t\022\r\n\005labe" +
      "l\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\"\336\001\n\013Payment" +
      "Data\022\023\n\013api_version\030\001 \001(\r\022\031\n\021api_version" +
      "_minor\030\002 \001(\r\022\r\n\005email\030\003 \001(\t\022%\n\020shipping_" +
      "address\030\004 \001(\0132\013.pb.Address\0222\n\023payment_me" +
      "thod_data\030\005 \001(\0132\025.pb.PaymentMethodData\0225" +
      "\n\024shipping_option_data\030\006 \001(\0132\027.pb.Select" +
      "ionOptionData\"!\n\023SelectionOptionData\022\n\n\002" +
      "id\030\001 \001(\t\"\220\001\n\021PaymentMethodData\022\014\n\004type\030\001" +
      " \001(\t\022\032\n\004info\030\002 \001(\0132\014.pb.CardInfo\022\023\n\013desc" +
      "ription\030\003 \001(\t\022<\n\021tokenization_data\030\004 \001(\013" +
      "2!.pb.PaymentMethodTokenizationData\"\\\n\010C" +
      "ardInfo\022\024\n\014card_network\030\001 \001(\t\022\024\n\014card_de" +
      "tails\030\002 \001(\t\022$\n\017billing_address\030\003 \001(\0132\013.p" +
      "b.Address\"\323\001\n\007Address\022\014\n\004name\030\001 \001(\t\022\020\n\010a" +
      "ddress1\030\002 \001(\t\022\020\n\010address2\030\003 \001(\t\022\020\n\010addre" +
      "ss3\030\004 \001(\t\022\020\n\010locality\030\005 \001(\t\022\033\n\023administr" +
      "ative_area\030\006 \001(\t\022\024\n\014country_code\030\007 \001(\t\022\023" +
      "\n\013postal_code\030\010 \001(\t\022\024\n\014sorting_code\030\t \001(" +
      "\t\022\024\n\014phone_number\030\n \001(\t\"<\n\035PaymentMethod" +
      "TokenizationData\022\014\n\004type\030\001 \001(\t\022\r\n\005token\030" +
      "\002 \001(\t\"\225\001\n\032PaymentMethodSpecification\022\014\n\004" +
      "type\030\001 \001(\t\022&\n\nparameters\030\002 \001(\0132\022.pb.Card" +
      "Parameters\022A\n\032tokenization_specification" +
      "\030\003 \001(\0132\035.pb.TokenizationSpecification\"\246\002" +
      "\n\016CardParameters\022\034\n\024allowed_auth_methods" +
      "\030\001 \003(\t\022\035\n\025allowed_card_networks\030\002 \003(\t\022\033\n" +
      "\023allow_prepaid_cards\030\003 \001(\010\022\032\n\022allow_cred" +
      "it_cards\030\004 \001(\010\022 \n\030billing_address_requir" +
      "ed\030\005 \001(\010\022@\n\032billing_address_parameters\030\006" +
      " \001(\0132\034.pb.BillingAddressParameters\022:\n\027ca" +
      "rd_network_parameters\030\007 \001(\0132\031.pb.CardNet" +
      "workParameters\"\237\001\n\031TokenizationSpecifica" +
      "tion\022\014\n\004type\030\001 \001(\t\022A\n\nparameters\030\002 \003(\0132-" +
      ".pb.TokenizationSpecification.Parameters" +
      "Entry\0321\n\017ParametersEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t:\0028\001\"I\n\030BillingAddressParame" +
      "ters\022\016\n\006format\030\001 \001(\t\022\035\n\025phone_number_req" +
      "uired\030\002 \001(\010\"a\n\025CardNetworkParameters\022\024\n\014" +
      "card_network\030\001 \001(\t\022\024\n\014acquirer_bin\030\002 \001(\t" +
      "\022\034\n\024acquirer_merchant_id\030\003 \001(\t\"A\n\013Mobile" +
      "Error\022\014\n\004code\030\001 \001(\r\022\017\n\007message\030\002 \001(\t\022\023\n\013" +
      "description\030\003 \001(\t\"k\n\032ApplePayPaymentData" +
      "Request\022\024\n\014country_code\030\001 \001(\t\022\025\n\rcurrenc" +
      "y_code\030\002 \001(\t\022 \n\005total\030\003 \001(\0132\021.pb.ApplePa" +
      "yTotal\".\n\rApplePayTotal\022\r\n\005label\030\001 \001(\t\022\016" +
      "\n\006amount\030\002 \001(\t\">\n\023ApplePayPaymentData\022\'\n" +
      "\005token\030\001 \001(\0132\030.pb.ApplePayPaymentToken\"|" +
      "\n\024ApplePayPaymentToken\022\024\n\014payment_data\030\001" +
      " \001(\t\022\036\n\026transaction_identifier\030\002 \001(\t\022.\n\016" +
      "payment_method\030\003 \001(\0132\026.pb.ApplePaymentMe" +
      "thod\";\n\022ApplePaymentMethod\022\024\n\014display_na" +
      "me\030\001 \001(\t\022\017\n\007network\030\002 \001(\t*\376\004\n\017MobileEven" +
      "tType\022\034\n\030MOBILE_EVENT_UNSPECIFIED\020\000\0222\n.M" +
      "OBILE_EVENT_GOOGLEPAY_IS_READY_TO_PAY_RE" +
      "QUEST\020\001\0223\n/MOBILE_EVENT_GOOGLEPAY_IS_REA" +
      "DY_TO_PAY_RESPONSE\020\002\022/\n+MOBILE_EVENT_GOO" +
      "GLEPAY_PAYMENT_DATA_REQUEST\020\003\0220\n,MOBILE_" +
      "EVENT_GOOGLEPAY_PAYMENT_DATA_RESPONSE\020\004\022" +
      "-\n)MOBILE_EVENT_GOOGLEPAY_PAYMENT_DATA_E" +
      "RROR\020\005\0221\n-MOBILE_EVENT_APPLEPAY_IS_READY" +
      "_TO_PAY_REQUEST\020\006\0222\n.MOBILE_EVENT_APPLEP" +
      "AY_IS_READY_TO_PAY_RESPONSE\020\007\022.\n*MOBILE_" +
      "EVENT_APPLEPAY_PAYMENT_DATA_REQUEST\020\010\022/\n" +
      "+MOBILE_EVENT_APPLEPAY_PAYMENT_DATA_RESP" +
      "ONSE\020\t\022,\n(MOBILE_EVENT_APPLEPAY_PAYMENT_" +
      "DATA_ERROR\020\n\022!\n\035MOBILE_EVENT_OPEN_URL_RE" +
      "QUEST\020\013\022\025\n\021MOBILE_EVENT_BACK\020\014\022\"\n\036MOBILE" +
      "_EVENT_SHARE_URL_REQUEST\020\rB\034\n\030ru.pnhub.w" +
      "idgetsdk.modelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pb_MobileEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_MobileEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_MobileEvent_descriptor,
        new java.lang.String[] { "Type", "Error", "IsReadyToPayRequest", "PaymentDataRequest", "IsReadyToPay", "PaymentData", "ApplepayPaymentDataRequest", "ApplepayPaymentData", "OpenUrlRequest", "ShareUrlRequest", "Payload", });
    internal_static_pb_IsReadyToPayRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_IsReadyToPayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_IsReadyToPayRequest_descriptor,
        new java.lang.String[] { "ApiVersion", "ApiVersionMinor", "AllowedPaymentMethods", "ExistingPaymentMethodRequired", });
    internal_static_pb_PaymentDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_PaymentDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PaymentDataRequest_descriptor,
        new java.lang.String[] { "MerchantInfo", "ApiVersion", "ApiVersionMinor", "EmailRequired", "ShippingAddressRequired", "ShippingAddressParameters", "AllowedPaymentMethods", "TransactionInfo", "ShippingOptionRequired", "ShippingOptionParameters", });
    internal_static_pb_MerchantInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pb_MerchantInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_MerchantInfo_descriptor,
        new java.lang.String[] { "MerchantId", "MerchantName", });
    internal_static_pb_ShippingAddressParameters_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pb_ShippingAddressParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ShippingAddressParameters_descriptor,
        new java.lang.String[] { "AllowedCountryCodes", "PhoneNumberRequired", });
    internal_static_pb_TransactionInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pb_TransactionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_TransactionInfo_descriptor,
        new java.lang.String[] { "TransactionId", "CurrencyCode", "CountryCode", "TotalPrice", "TotalPriceLabel", "TotalPriceStatus", "TransactionNote", "CheckoutOption", "DisplayItems", });
    internal_static_pb_DisplayItem_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pb_DisplayItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_DisplayItem_descriptor,
        new java.lang.String[] { "Label", "Type", "Price", "Status", });
    internal_static_pb_ShippingOptionParameters_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_pb_ShippingOptionParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ShippingOptionParameters_descriptor,
        new java.lang.String[] { "ShippingOptions", "DefaultSelectedOptionId", });
    internal_static_pb_ShippingOption_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_pb_ShippingOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ShippingOption_descriptor,
        new java.lang.String[] { "Id", "Label", "Description", });
    internal_static_pb_PaymentData_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_pb_PaymentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PaymentData_descriptor,
        new java.lang.String[] { "ApiVersion", "ApiVersionMinor", "Email", "ShippingAddress", "PaymentMethodData", "ShippingOptionData", });
    internal_static_pb_SelectionOptionData_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_pb_SelectionOptionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SelectionOptionData_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_pb_PaymentMethodData_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_pb_PaymentMethodData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PaymentMethodData_descriptor,
        new java.lang.String[] { "Type", "Info", "Description", "TokenizationData", });
    internal_static_pb_CardInfo_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_pb_CardInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_CardInfo_descriptor,
        new java.lang.String[] { "CardNetwork", "CardDetails", "BillingAddress", });
    internal_static_pb_Address_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_pb_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Address_descriptor,
        new java.lang.String[] { "Name", "Address1", "Address2", "Address3", "Locality", "AdministrativeArea", "CountryCode", "PostalCode", "SortingCode", "PhoneNumber", });
    internal_static_pb_PaymentMethodTokenizationData_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_pb_PaymentMethodTokenizationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PaymentMethodTokenizationData_descriptor,
        new java.lang.String[] { "Type", "Token", });
    internal_static_pb_PaymentMethodSpecification_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_pb_PaymentMethodSpecification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PaymentMethodSpecification_descriptor,
        new java.lang.String[] { "Type", "Parameters", "TokenizationSpecification", });
    internal_static_pb_CardParameters_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_pb_CardParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_CardParameters_descriptor,
        new java.lang.String[] { "AllowedAuthMethods", "AllowedCardNetworks", "AllowPrepaidCards", "AllowCreditCards", "BillingAddressRequired", "BillingAddressParameters", "CardNetworkParameters", });
    internal_static_pb_TokenizationSpecification_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_pb_TokenizationSpecification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_TokenizationSpecification_descriptor,
        new java.lang.String[] { "Type", "Parameters", });
    internal_static_pb_TokenizationSpecification_ParametersEntry_descriptor =
      internal_static_pb_TokenizationSpecification_descriptor.getNestedTypes().get(0);
    internal_static_pb_TokenizationSpecification_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_TokenizationSpecification_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pb_BillingAddressParameters_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_pb_BillingAddressParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_BillingAddressParameters_descriptor,
        new java.lang.String[] { "Format", "PhoneNumberRequired", });
    internal_static_pb_CardNetworkParameters_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_pb_CardNetworkParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_CardNetworkParameters_descriptor,
        new java.lang.String[] { "CardNetwork", "AcquirerBin", "AcquirerMerchantId", });
    internal_static_pb_MobileError_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_pb_MobileError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_MobileError_descriptor,
        new java.lang.String[] { "Code", "Message", "Description", });
    internal_static_pb_ApplePayPaymentDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_pb_ApplePayPaymentDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ApplePayPaymentDataRequest_descriptor,
        new java.lang.String[] { "CountryCode", "CurrencyCode", "Total", });
    internal_static_pb_ApplePayTotal_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_pb_ApplePayTotal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ApplePayTotal_descriptor,
        new java.lang.String[] { "Label", "Amount", });
    internal_static_pb_ApplePayPaymentData_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_pb_ApplePayPaymentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ApplePayPaymentData_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_pb_ApplePayPaymentToken_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_pb_ApplePayPaymentToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ApplePayPaymentToken_descriptor,
        new java.lang.String[] { "PaymentData", "TransactionIdentifier", "PaymentMethod", });
    internal_static_pb_ApplePaymentMethod_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_pb_ApplePaymentMethod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ApplePaymentMethod_descriptor,
        new java.lang.String[] { "DisplayName", "Network", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
