// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

public interface PaymentDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.PaymentDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pb.MerchantInfo merchant_info = 1;</code>
   * @return Whether the merchantInfo field is set.
   */
  boolean hasMerchantInfo();
  /**
   * <code>.pb.MerchantInfo merchant_info = 1;</code>
   * @return The merchantInfo.
   */
  MerchantInfo getMerchantInfo();
  /**
   * <code>.pb.MerchantInfo merchant_info = 1;</code>
   */
  MerchantInfoOrBuilder getMerchantInfoOrBuilder();

  /**
   * <code>uint32 api_version = 2;</code>
   * @return The apiVersion.
   */
  int getApiVersion();

  /**
   * <code>uint32 api_version_minor = 3;</code>
   * @return The apiVersionMinor.
   */
  int getApiVersionMinor();

  /**
   * <code>bool email_required = 4;</code>
   * @return The emailRequired.
   */
  boolean getEmailRequired();

  /**
   * <code>bool shipping_address_required = 5;</code>
   * @return The shippingAddressRequired.
   */
  boolean getShippingAddressRequired();

  /**
   * <code>.pb.ShippingAddressParameters shipping_address_parameters = 6;</code>
   * @return Whether the shippingAddressParameters field is set.
   */
  boolean hasShippingAddressParameters();
  /**
   * <code>.pb.ShippingAddressParameters shipping_address_parameters = 6;</code>
   * @return The shippingAddressParameters.
   */
  ShippingAddressParameters getShippingAddressParameters();
  /**
   * <code>.pb.ShippingAddressParameters shipping_address_parameters = 6;</code>
   */
  ShippingAddressParametersOrBuilder getShippingAddressParametersOrBuilder();

  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  java.util.List<PaymentMethodSpecification>
      getAllowedPaymentMethodsList();
  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  PaymentMethodSpecification getAllowedPaymentMethods(int index);
  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  int getAllowedPaymentMethodsCount();
  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  java.util.List<? extends PaymentMethodSpecificationOrBuilder>
      getAllowedPaymentMethodsOrBuilderList();
  /**
   * <code>repeated .pb.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  PaymentMethodSpecificationOrBuilder getAllowedPaymentMethodsOrBuilder(
      int index);

  /**
   * <code>.pb.TransactionInfo transaction_info = 8;</code>
   * @return Whether the transactionInfo field is set.
   */
  boolean hasTransactionInfo();
  /**
   * <code>.pb.TransactionInfo transaction_info = 8;</code>
   * @return The transactionInfo.
   */
  TransactionInfo getTransactionInfo();
  /**
   * <code>.pb.TransactionInfo transaction_info = 8;</code>
   */
  TransactionInfoOrBuilder getTransactionInfoOrBuilder();

  /**
   * <code>bool shipping_option_required = 9;</code>
   * @return The shippingOptionRequired.
   */
  boolean getShippingOptionRequired();

  /**
   * <code>.pb.ShippingOptionParameters shipping_option_parameters = 10;</code>
   * @return Whether the shippingOptionParameters field is set.
   */
  boolean hasShippingOptionParameters();
  /**
   * <code>.pb.ShippingOptionParameters shipping_option_parameters = 10;</code>
   * @return The shippingOptionParameters.
   */
  ShippingOptionParameters getShippingOptionParameters();
  /**
   * <code>.pb.ShippingOptionParameters shipping_option_parameters = 10;</code>
   */
  ShippingOptionParametersOrBuilder getShippingOptionParametersOrBuilder();
}
