// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

/**
 * Protobuf type {@code pb.PaymentData}
 */
public final class PaymentData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.PaymentData)
    PaymentDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaymentData.newBuilder() to construct.
  private PaymentData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaymentData() {
    email_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new PaymentData();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PaymentData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            apiVersion_ = input.readUInt32();
            break;
          }
          case 16: {

            apiVersionMinor_ = input.readUInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 34: {
            Address.Builder subBuilder = null;
            if (shippingAddress_ != null) {
              subBuilder = shippingAddress_.toBuilder();
            }
            shippingAddress_ = input.readMessage(Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(shippingAddress_);
              shippingAddress_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            PaymentMethodData.Builder subBuilder = null;
            if (paymentMethodData_ != null) {
              subBuilder = paymentMethodData_.toBuilder();
            }
            paymentMethodData_ = input.readMessage(PaymentMethodData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(paymentMethodData_);
              paymentMethodData_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            SelectionOptionData.Builder subBuilder = null;
            if (shippingOptionData_ != null) {
              subBuilder = shippingOptionData_.toBuilder();
            }
            shippingOptionData_ = input.readMessage(SelectionOptionData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(shippingOptionData_);
              shippingOptionData_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MobileModel.internal_static_pb_PaymentData_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MobileModel.internal_static_pb_PaymentData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PaymentData.class, Builder.class);
  }

  public static final int API_VERSION_FIELD_NUMBER = 1;
  private int apiVersion_;
  /**
   * <code>uint32 api_version = 1;</code>
   * @return The apiVersion.
   */
  @Override
  public int getApiVersion() {
    return apiVersion_;
  }

  public static final int API_VERSION_MINOR_FIELD_NUMBER = 2;
  private int apiVersionMinor_;
  /**
   * <code>uint32 api_version_minor = 2;</code>
   * @return The apiVersionMinor.
   */
  @Override
  public int getApiVersionMinor() {
    return apiVersionMinor_;
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private volatile Object email_;
  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  @Override
  public String getEmail() {
    Object ref = email_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  @Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    Object ref = email_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHIPPING_ADDRESS_FIELD_NUMBER = 4;
  private Address shippingAddress_;
  /**
   * <code>.pb.Address shipping_address = 4;</code>
   * @return Whether the shippingAddress field is set.
   */
  @Override
  public boolean hasShippingAddress() {
    return shippingAddress_ != null;
  }
  /**
   * <code>.pb.Address shipping_address = 4;</code>
   * @return The shippingAddress.
   */
  @Override
  public Address getShippingAddress() {
    return shippingAddress_ == null ? Address.getDefaultInstance() : shippingAddress_;
  }
  /**
   * <code>.pb.Address shipping_address = 4;</code>
   */
  @Override
  public AddressOrBuilder getShippingAddressOrBuilder() {
    return getShippingAddress();
  }

  public static final int PAYMENT_METHOD_DATA_FIELD_NUMBER = 5;
  private PaymentMethodData paymentMethodData_;
  /**
   * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
   * @return Whether the paymentMethodData field is set.
   */
  @Override
  public boolean hasPaymentMethodData() {
    return paymentMethodData_ != null;
  }
  /**
   * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
   * @return The paymentMethodData.
   */
  @Override
  public PaymentMethodData getPaymentMethodData() {
    return paymentMethodData_ == null ? PaymentMethodData.getDefaultInstance() : paymentMethodData_;
  }
  /**
   * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
   */
  @Override
  public PaymentMethodDataOrBuilder getPaymentMethodDataOrBuilder() {
    return getPaymentMethodData();
  }

  public static final int SHIPPING_OPTION_DATA_FIELD_NUMBER = 6;
  private SelectionOptionData shippingOptionData_;
  /**
   * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
   * @return Whether the shippingOptionData field is set.
   */
  @Override
  public boolean hasShippingOptionData() {
    return shippingOptionData_ != null;
  }
  /**
   * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
   * @return The shippingOptionData.
   */
  @Override
  public SelectionOptionData getShippingOptionData() {
    return shippingOptionData_ == null ? SelectionOptionData.getDefaultInstance() : shippingOptionData_;
  }
  /**
   * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
   */
  @Override
  public SelectionOptionDataOrBuilder getShippingOptionDataOrBuilder() {
    return getShippingOptionData();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (apiVersion_ != 0) {
      output.writeUInt32(1, apiVersion_);
    }
    if (apiVersionMinor_ != 0) {
      output.writeUInt32(2, apiVersionMinor_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    if (shippingAddress_ != null) {
      output.writeMessage(4, getShippingAddress());
    }
    if (paymentMethodData_ != null) {
      output.writeMessage(5, getPaymentMethodData());
    }
    if (shippingOptionData_ != null) {
      output.writeMessage(6, getShippingOptionData());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (apiVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, apiVersion_);
    }
    if (apiVersionMinor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, apiVersionMinor_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    if (shippingAddress_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getShippingAddress());
    }
    if (paymentMethodData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPaymentMethodData());
    }
    if (shippingOptionData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getShippingOptionData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PaymentData)) {
      return super.equals(obj);
    }
    PaymentData other = (PaymentData) obj;

    if (getApiVersion()
        != other.getApiVersion()) return false;
    if (getApiVersionMinor()
        != other.getApiVersionMinor()) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (hasShippingAddress() != other.hasShippingAddress()) return false;
    if (hasShippingAddress()) {
      if (!getShippingAddress()
          .equals(other.getShippingAddress())) return false;
    }
    if (hasPaymentMethodData() != other.hasPaymentMethodData()) return false;
    if (hasPaymentMethodData()) {
      if (!getPaymentMethodData()
          .equals(other.getPaymentMethodData())) return false;
    }
    if (hasShippingOptionData() != other.hasShippingOptionData()) return false;
    if (hasShippingOptionData()) {
      if (!getShippingOptionData()
          .equals(other.getShippingOptionData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + API_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getApiVersion();
    hash = (37 * hash) + API_VERSION_MINOR_FIELD_NUMBER;
    hash = (53 * hash) + getApiVersionMinor();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (hasShippingAddress()) {
      hash = (37 * hash) + SHIPPING_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getShippingAddress().hashCode();
    }
    if (hasPaymentMethodData()) {
      hash = (37 * hash) + PAYMENT_METHOD_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentMethodData().hashCode();
    }
    if (hasShippingOptionData()) {
      hash = (37 * hash) + SHIPPING_OPTION_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getShippingOptionData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PaymentData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PaymentData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PaymentData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PaymentData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PaymentData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PaymentData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PaymentData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PaymentData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static PaymentData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static PaymentData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PaymentData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PaymentData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PaymentData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.PaymentData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.PaymentData)
      PaymentDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MobileModel.internal_static_pb_PaymentData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MobileModel.internal_static_pb_PaymentData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PaymentData.class, Builder.class);
    }

    // Construct using ru.pnhub.widgetsdk.model.PaymentData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      apiVersion_ = 0;

      apiVersionMinor_ = 0;

      email_ = "";

      if (shippingAddressBuilder_ == null) {
        shippingAddress_ = null;
      } else {
        shippingAddress_ = null;
        shippingAddressBuilder_ = null;
      }
      if (paymentMethodDataBuilder_ == null) {
        paymentMethodData_ = null;
      } else {
        paymentMethodData_ = null;
        paymentMethodDataBuilder_ = null;
      }
      if (shippingOptionDataBuilder_ == null) {
        shippingOptionData_ = null;
      } else {
        shippingOptionData_ = null;
        shippingOptionDataBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MobileModel.internal_static_pb_PaymentData_descriptor;
    }

    @Override
    public PaymentData getDefaultInstanceForType() {
      return PaymentData.getDefaultInstance();
    }

    @Override
    public PaymentData build() {
      PaymentData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PaymentData buildPartial() {
      PaymentData result = new PaymentData(this);
      result.apiVersion_ = apiVersion_;
      result.apiVersionMinor_ = apiVersionMinor_;
      result.email_ = email_;
      if (shippingAddressBuilder_ == null) {
        result.shippingAddress_ = shippingAddress_;
      } else {
        result.shippingAddress_ = shippingAddressBuilder_.build();
      }
      if (paymentMethodDataBuilder_ == null) {
        result.paymentMethodData_ = paymentMethodData_;
      } else {
        result.paymentMethodData_ = paymentMethodDataBuilder_.build();
      }
      if (shippingOptionDataBuilder_ == null) {
        result.shippingOptionData_ = shippingOptionData_;
      } else {
        result.shippingOptionData_ = shippingOptionDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PaymentData) {
        return mergeFrom((PaymentData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PaymentData other) {
      if (other == PaymentData.getDefaultInstance()) return this;
      if (other.getApiVersion() != 0) {
        setApiVersion(other.getApiVersion());
      }
      if (other.getApiVersionMinor() != 0) {
        setApiVersionMinor(other.getApiVersionMinor());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (other.hasShippingAddress()) {
        mergeShippingAddress(other.getShippingAddress());
      }
      if (other.hasPaymentMethodData()) {
        mergePaymentMethodData(other.getPaymentMethodData());
      }
      if (other.hasShippingOptionData()) {
        mergeShippingOptionData(other.getShippingOptionData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      PaymentData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (PaymentData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int apiVersion_ ;
    /**
     * <code>uint32 api_version = 1;</code>
     * @return The apiVersion.
     */
    @Override
    public int getApiVersion() {
      return apiVersion_;
    }
    /**
     * <code>uint32 api_version = 1;</code>
     * @param value The apiVersion to set.
     * @return This builder for chaining.
     */
    public Builder setApiVersion(int value) {
      
      apiVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 api_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearApiVersion() {
      
      apiVersion_ = 0;
      onChanged();
      return this;
    }

    private int apiVersionMinor_ ;
    /**
     * <code>uint32 api_version_minor = 2;</code>
     * @return The apiVersionMinor.
     */
    @Override
    public int getApiVersionMinor() {
      return apiVersionMinor_;
    }
    /**
     * <code>uint32 api_version_minor = 2;</code>
     * @param value The apiVersionMinor to set.
     * @return This builder for chaining.
     */
    public Builder setApiVersionMinor(int value) {
      
      apiVersionMinor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 api_version_minor = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearApiVersionMinor() {
      
      apiVersionMinor_ = 0;
      onChanged();
      return this;
    }

    private Object email_ = "";
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public String getEmail() {
      Object ref = email_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private Address shippingAddress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Address, Address.Builder, AddressOrBuilder> shippingAddressBuilder_;
    /**
     * <code>.pb.Address shipping_address = 4;</code>
     * @return Whether the shippingAddress field is set.
     */
    public boolean hasShippingAddress() {
      return shippingAddressBuilder_ != null || shippingAddress_ != null;
    }
    /**
     * <code>.pb.Address shipping_address = 4;</code>
     * @return The shippingAddress.
     */
    public Address getShippingAddress() {
      if (shippingAddressBuilder_ == null) {
        return shippingAddress_ == null ? Address.getDefaultInstance() : shippingAddress_;
      } else {
        return shippingAddressBuilder_.getMessage();
      }
    }
    /**
     * <code>.pb.Address shipping_address = 4;</code>
     */
    public Builder setShippingAddress(Address value) {
      if (shippingAddressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shippingAddress_ = value;
        onChanged();
      } else {
        shippingAddressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pb.Address shipping_address = 4;</code>
     */
    public Builder setShippingAddress(
        Address.Builder builderForValue) {
      if (shippingAddressBuilder_ == null) {
        shippingAddress_ = builderForValue.build();
        onChanged();
      } else {
        shippingAddressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pb.Address shipping_address = 4;</code>
     */
    public Builder mergeShippingAddress(Address value) {
      if (shippingAddressBuilder_ == null) {
        if (shippingAddress_ != null) {
          shippingAddress_ =
            Address.newBuilder(shippingAddress_).mergeFrom(value).buildPartial();
        } else {
          shippingAddress_ = value;
        }
        onChanged();
      } else {
        shippingAddressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pb.Address shipping_address = 4;</code>
     */
    public Builder clearShippingAddress() {
      if (shippingAddressBuilder_ == null) {
        shippingAddress_ = null;
        onChanged();
      } else {
        shippingAddress_ = null;
        shippingAddressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pb.Address shipping_address = 4;</code>
     */
    public Address.Builder getShippingAddressBuilder() {
      
      onChanged();
      return getShippingAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.pb.Address shipping_address = 4;</code>
     */
    public AddressOrBuilder getShippingAddressOrBuilder() {
      if (shippingAddressBuilder_ != null) {
        return shippingAddressBuilder_.getMessageOrBuilder();
      } else {
        return shippingAddress_ == null ?
            Address.getDefaultInstance() : shippingAddress_;
      }
    }
    /**
     * <code>.pb.Address shipping_address = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Address, Address.Builder, AddressOrBuilder>
        getShippingAddressFieldBuilder() {
      if (shippingAddressBuilder_ == null) {
        shippingAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Address, Address.Builder, AddressOrBuilder>(
                getShippingAddress(),
                getParentForChildren(),
                isClean());
        shippingAddress_ = null;
      }
      return shippingAddressBuilder_;
    }

    private PaymentMethodData paymentMethodData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        PaymentMethodData, PaymentMethodData.Builder, PaymentMethodDataOrBuilder> paymentMethodDataBuilder_;
    /**
     * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
     * @return Whether the paymentMethodData field is set.
     */
    public boolean hasPaymentMethodData() {
      return paymentMethodDataBuilder_ != null || paymentMethodData_ != null;
    }
    /**
     * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
     * @return The paymentMethodData.
     */
    public PaymentMethodData getPaymentMethodData() {
      if (paymentMethodDataBuilder_ == null) {
        return paymentMethodData_ == null ? PaymentMethodData.getDefaultInstance() : paymentMethodData_;
      } else {
        return paymentMethodDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
     */
    public Builder setPaymentMethodData(PaymentMethodData value) {
      if (paymentMethodDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paymentMethodData_ = value;
        onChanged();
      } else {
        paymentMethodDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
     */
    public Builder setPaymentMethodData(
        PaymentMethodData.Builder builderForValue) {
      if (paymentMethodDataBuilder_ == null) {
        paymentMethodData_ = builderForValue.build();
        onChanged();
      } else {
        paymentMethodDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
     */
    public Builder mergePaymentMethodData(PaymentMethodData value) {
      if (paymentMethodDataBuilder_ == null) {
        if (paymentMethodData_ != null) {
          paymentMethodData_ =
            PaymentMethodData.newBuilder(paymentMethodData_).mergeFrom(value).buildPartial();
        } else {
          paymentMethodData_ = value;
        }
        onChanged();
      } else {
        paymentMethodDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
     */
    public Builder clearPaymentMethodData() {
      if (paymentMethodDataBuilder_ == null) {
        paymentMethodData_ = null;
        onChanged();
      } else {
        paymentMethodData_ = null;
        paymentMethodDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
     */
    public PaymentMethodData.Builder getPaymentMethodDataBuilder() {
      
      onChanged();
      return getPaymentMethodDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
     */
    public PaymentMethodDataOrBuilder getPaymentMethodDataOrBuilder() {
      if (paymentMethodDataBuilder_ != null) {
        return paymentMethodDataBuilder_.getMessageOrBuilder();
      } else {
        return paymentMethodData_ == null ?
            PaymentMethodData.getDefaultInstance() : paymentMethodData_;
      }
    }
    /**
     * <code>.pb.PaymentMethodData payment_method_data = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        PaymentMethodData, PaymentMethodData.Builder, PaymentMethodDataOrBuilder>
        getPaymentMethodDataFieldBuilder() {
      if (paymentMethodDataBuilder_ == null) {
        paymentMethodDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            PaymentMethodData, PaymentMethodData.Builder, PaymentMethodDataOrBuilder>(
                getPaymentMethodData(),
                getParentForChildren(),
                isClean());
        paymentMethodData_ = null;
      }
      return paymentMethodDataBuilder_;
    }

    private SelectionOptionData shippingOptionData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        SelectionOptionData, SelectionOptionData.Builder, SelectionOptionDataOrBuilder> shippingOptionDataBuilder_;
    /**
     * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
     * @return Whether the shippingOptionData field is set.
     */
    public boolean hasShippingOptionData() {
      return shippingOptionDataBuilder_ != null || shippingOptionData_ != null;
    }
    /**
     * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
     * @return The shippingOptionData.
     */
    public SelectionOptionData getShippingOptionData() {
      if (shippingOptionDataBuilder_ == null) {
        return shippingOptionData_ == null ? SelectionOptionData.getDefaultInstance() : shippingOptionData_;
      } else {
        return shippingOptionDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
     */
    public Builder setShippingOptionData(SelectionOptionData value) {
      if (shippingOptionDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shippingOptionData_ = value;
        onChanged();
      } else {
        shippingOptionDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
     */
    public Builder setShippingOptionData(
        SelectionOptionData.Builder builderForValue) {
      if (shippingOptionDataBuilder_ == null) {
        shippingOptionData_ = builderForValue.build();
        onChanged();
      } else {
        shippingOptionDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
     */
    public Builder mergeShippingOptionData(SelectionOptionData value) {
      if (shippingOptionDataBuilder_ == null) {
        if (shippingOptionData_ != null) {
          shippingOptionData_ =
            SelectionOptionData.newBuilder(shippingOptionData_).mergeFrom(value).buildPartial();
        } else {
          shippingOptionData_ = value;
        }
        onChanged();
      } else {
        shippingOptionDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
     */
    public Builder clearShippingOptionData() {
      if (shippingOptionDataBuilder_ == null) {
        shippingOptionData_ = null;
        onChanged();
      } else {
        shippingOptionData_ = null;
        shippingOptionDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
     */
    public SelectionOptionData.Builder getShippingOptionDataBuilder() {
      
      onChanged();
      return getShippingOptionDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
     */
    public SelectionOptionDataOrBuilder getShippingOptionDataOrBuilder() {
      if (shippingOptionDataBuilder_ != null) {
        return shippingOptionDataBuilder_.getMessageOrBuilder();
      } else {
        return shippingOptionData_ == null ?
            SelectionOptionData.getDefaultInstance() : shippingOptionData_;
      }
    }
    /**
     * <code>.pb.SelectionOptionData shipping_option_data = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        SelectionOptionData, SelectionOptionData.Builder, SelectionOptionDataOrBuilder>
        getShippingOptionDataFieldBuilder() {
      if (shippingOptionDataBuilder_ == null) {
        shippingOptionDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            SelectionOptionData, SelectionOptionData.Builder, SelectionOptionDataOrBuilder>(
                getShippingOptionData(),
                getParentForChildren(),
                isClean());
        shippingOptionData_ = null;
      }
      return shippingOptionDataBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.PaymentData)
  }

  // @@protoc_insertion_point(class_scope:pb.PaymentData)
  private static final PaymentData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PaymentData();
  }

  public static PaymentData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaymentData>
      PARSER = new com.google.protobuf.AbstractParser<PaymentData>() {
    @Override
    public PaymentData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PaymentData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PaymentData> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PaymentData> getParserForType() {
    return PARSER;
  }

  @Override
  public PaymentData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

