// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

public interface ShippingOptionParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.ShippingOptionParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  java.util.List<ShippingOption>
      getShippingOptionsList();
  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  ShippingOption getShippingOptions(int index);
  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  int getShippingOptionsCount();
  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  java.util.List<? extends ShippingOptionOrBuilder>
      getShippingOptionsOrBuilderList();
  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  ShippingOptionOrBuilder getShippingOptionsOrBuilder(
      int index);

  /**
   * <code>string default_selected_option_id = 2;</code>
   * @return The defaultSelectedOptionId.
   */
  String getDefaultSelectedOptionId();
  /**
   * <code>string default_selected_option_id = 2;</code>
   * @return The bytes for defaultSelectedOptionId.
   */
  com.google.protobuf.ByteString
      getDefaultSelectedOptionIdBytes();
}
