// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

/**
 * Protobuf type {@code pb.ShippingOptionParameters}
 */
public final class ShippingOptionParameters extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.ShippingOptionParameters)
    ShippingOptionParametersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShippingOptionParameters.newBuilder() to construct.
  private ShippingOptionParameters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShippingOptionParameters() {
    shippingOptions_ = java.util.Collections.emptyList();
    defaultSelectedOptionId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ShippingOptionParameters();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShippingOptionParameters(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              shippingOptions_ = new java.util.ArrayList<ShippingOption>();
              mutable_bitField0_ |= 0x00000001;
            }
            shippingOptions_.add(
                input.readMessage(ShippingOption.parser(), extensionRegistry));
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            defaultSelectedOptionId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        shippingOptions_ = java.util.Collections.unmodifiableList(shippingOptions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MobileModel.internal_static_pb_ShippingOptionParameters_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MobileModel.internal_static_pb_ShippingOptionParameters_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ShippingOptionParameters.class, Builder.class);
  }

  public static final int SHIPPING_OPTIONS_FIELD_NUMBER = 1;
  private java.util.List<ShippingOption> shippingOptions_;
  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  @Override
  public java.util.List<ShippingOption> getShippingOptionsList() {
    return shippingOptions_;
  }
  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  @Override
  public java.util.List<? extends ShippingOptionOrBuilder>
      getShippingOptionsOrBuilderList() {
    return shippingOptions_;
  }
  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  @Override
  public int getShippingOptionsCount() {
    return shippingOptions_.size();
  }
  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  @Override
  public ShippingOption getShippingOptions(int index) {
    return shippingOptions_.get(index);
  }
  /**
   * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
   */
  @Override
  public ShippingOptionOrBuilder getShippingOptionsOrBuilder(
      int index) {
    return shippingOptions_.get(index);
  }

  public static final int DEFAULT_SELECTED_OPTION_ID_FIELD_NUMBER = 2;
  private volatile Object defaultSelectedOptionId_;
  /**
   * <code>string default_selected_option_id = 2;</code>
   * @return The defaultSelectedOptionId.
   */
  @Override
  public String getDefaultSelectedOptionId() {
    Object ref = defaultSelectedOptionId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      defaultSelectedOptionId_ = s;
      return s;
    }
  }
  /**
   * <code>string default_selected_option_id = 2;</code>
   * @return The bytes for defaultSelectedOptionId.
   */
  @Override
  public com.google.protobuf.ByteString
      getDefaultSelectedOptionIdBytes() {
    Object ref = defaultSelectedOptionId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      defaultSelectedOptionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < shippingOptions_.size(); i++) {
      output.writeMessage(1, shippingOptions_.get(i));
    }
    if (!getDefaultSelectedOptionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, defaultSelectedOptionId_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < shippingOptions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, shippingOptions_.get(i));
    }
    if (!getDefaultSelectedOptionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, defaultSelectedOptionId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ShippingOptionParameters)) {
      return super.equals(obj);
    }
    ShippingOptionParameters other = (ShippingOptionParameters) obj;

    if (!getShippingOptionsList()
        .equals(other.getShippingOptionsList())) return false;
    if (!getDefaultSelectedOptionId()
        .equals(other.getDefaultSelectedOptionId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getShippingOptionsCount() > 0) {
      hash = (37 * hash) + SHIPPING_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getShippingOptionsList().hashCode();
    }
    hash = (37 * hash) + DEFAULT_SELECTED_OPTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultSelectedOptionId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ShippingOptionParameters parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ShippingOptionParameters parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ShippingOptionParameters parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ShippingOptionParameters parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ShippingOptionParameters parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ShippingOptionParameters parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ShippingOptionParameters parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ShippingOptionParameters parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ShippingOptionParameters parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ShippingOptionParameters parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ShippingOptionParameters parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ShippingOptionParameters parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ShippingOptionParameters prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.ShippingOptionParameters}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.ShippingOptionParameters)
      ShippingOptionParametersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MobileModel.internal_static_pb_ShippingOptionParameters_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MobileModel.internal_static_pb_ShippingOptionParameters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ShippingOptionParameters.class, Builder.class);
    }

    // Construct using ru.pnhub.widgetsdk.model.ShippingOptionParameters.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getShippingOptionsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (shippingOptionsBuilder_ == null) {
        shippingOptions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        shippingOptionsBuilder_.clear();
      }
      defaultSelectedOptionId_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MobileModel.internal_static_pb_ShippingOptionParameters_descriptor;
    }

    @Override
    public ShippingOptionParameters getDefaultInstanceForType() {
      return ShippingOptionParameters.getDefaultInstance();
    }

    @Override
    public ShippingOptionParameters build() {
      ShippingOptionParameters result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ShippingOptionParameters buildPartial() {
      ShippingOptionParameters result = new ShippingOptionParameters(this);
      int from_bitField0_ = bitField0_;
      if (shippingOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          shippingOptions_ = java.util.Collections.unmodifiableList(shippingOptions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.shippingOptions_ = shippingOptions_;
      } else {
        result.shippingOptions_ = shippingOptionsBuilder_.build();
      }
      result.defaultSelectedOptionId_ = defaultSelectedOptionId_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ShippingOptionParameters) {
        return mergeFrom((ShippingOptionParameters)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ShippingOptionParameters other) {
      if (other == ShippingOptionParameters.getDefaultInstance()) return this;
      if (shippingOptionsBuilder_ == null) {
        if (!other.shippingOptions_.isEmpty()) {
          if (shippingOptions_.isEmpty()) {
            shippingOptions_ = other.shippingOptions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureShippingOptionsIsMutable();
            shippingOptions_.addAll(other.shippingOptions_);
          }
          onChanged();
        }
      } else {
        if (!other.shippingOptions_.isEmpty()) {
          if (shippingOptionsBuilder_.isEmpty()) {
            shippingOptionsBuilder_.dispose();
            shippingOptionsBuilder_ = null;
            shippingOptions_ = other.shippingOptions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            shippingOptionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getShippingOptionsFieldBuilder() : null;
          } else {
            shippingOptionsBuilder_.addAllMessages(other.shippingOptions_);
          }
        }
      }
      if (!other.getDefaultSelectedOptionId().isEmpty()) {
        defaultSelectedOptionId_ = other.defaultSelectedOptionId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ShippingOptionParameters parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ShippingOptionParameters) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ShippingOption> shippingOptions_ =
      java.util.Collections.emptyList();
    private void ensureShippingOptionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        shippingOptions_ = new java.util.ArrayList<ShippingOption>(shippingOptions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ShippingOption, ShippingOption.Builder, ShippingOptionOrBuilder> shippingOptionsBuilder_;

    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public java.util.List<ShippingOption> getShippingOptionsList() {
      if (shippingOptionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(shippingOptions_);
      } else {
        return shippingOptionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public int getShippingOptionsCount() {
      if (shippingOptionsBuilder_ == null) {
        return shippingOptions_.size();
      } else {
        return shippingOptionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public ShippingOption getShippingOptions(int index) {
      if (shippingOptionsBuilder_ == null) {
        return shippingOptions_.get(index);
      } else {
        return shippingOptionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public Builder setShippingOptions(
        int index, ShippingOption value) {
      if (shippingOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShippingOptionsIsMutable();
        shippingOptions_.set(index, value);
        onChanged();
      } else {
        shippingOptionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public Builder setShippingOptions(
        int index, ShippingOption.Builder builderForValue) {
      if (shippingOptionsBuilder_ == null) {
        ensureShippingOptionsIsMutable();
        shippingOptions_.set(index, builderForValue.build());
        onChanged();
      } else {
        shippingOptionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public Builder addShippingOptions(ShippingOption value) {
      if (shippingOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShippingOptionsIsMutable();
        shippingOptions_.add(value);
        onChanged();
      } else {
        shippingOptionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public Builder addShippingOptions(
        int index, ShippingOption value) {
      if (shippingOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShippingOptionsIsMutable();
        shippingOptions_.add(index, value);
        onChanged();
      } else {
        shippingOptionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public Builder addShippingOptions(
        ShippingOption.Builder builderForValue) {
      if (shippingOptionsBuilder_ == null) {
        ensureShippingOptionsIsMutable();
        shippingOptions_.add(builderForValue.build());
        onChanged();
      } else {
        shippingOptionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public Builder addShippingOptions(
        int index, ShippingOption.Builder builderForValue) {
      if (shippingOptionsBuilder_ == null) {
        ensureShippingOptionsIsMutable();
        shippingOptions_.add(index, builderForValue.build());
        onChanged();
      } else {
        shippingOptionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public Builder addAllShippingOptions(
        Iterable<? extends ShippingOption> values) {
      if (shippingOptionsBuilder_ == null) {
        ensureShippingOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, shippingOptions_);
        onChanged();
      } else {
        shippingOptionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public Builder clearShippingOptions() {
      if (shippingOptionsBuilder_ == null) {
        shippingOptions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        shippingOptionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public Builder removeShippingOptions(int index) {
      if (shippingOptionsBuilder_ == null) {
        ensureShippingOptionsIsMutable();
        shippingOptions_.remove(index);
        onChanged();
      } else {
        shippingOptionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public ShippingOption.Builder getShippingOptionsBuilder(
        int index) {
      return getShippingOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public ShippingOptionOrBuilder getShippingOptionsOrBuilder(
        int index) {
      if (shippingOptionsBuilder_ == null) {
        return shippingOptions_.get(index);  } else {
        return shippingOptionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public java.util.List<? extends ShippingOptionOrBuilder>
         getShippingOptionsOrBuilderList() {
      if (shippingOptionsBuilder_ != null) {
        return shippingOptionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(shippingOptions_);
      }
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public ShippingOption.Builder addShippingOptionsBuilder() {
      return getShippingOptionsFieldBuilder().addBuilder(
          ShippingOption.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public ShippingOption.Builder addShippingOptionsBuilder(
        int index) {
      return getShippingOptionsFieldBuilder().addBuilder(
          index, ShippingOption.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.ShippingOption shipping_options = 1;</code>
     */
    public java.util.List<ShippingOption.Builder>
         getShippingOptionsBuilderList() {
      return getShippingOptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ShippingOption, ShippingOption.Builder, ShippingOptionOrBuilder>
        getShippingOptionsFieldBuilder() {
      if (shippingOptionsBuilder_ == null) {
        shippingOptionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ShippingOption, ShippingOption.Builder, ShippingOptionOrBuilder>(
                shippingOptions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        shippingOptions_ = null;
      }
      return shippingOptionsBuilder_;
    }

    private Object defaultSelectedOptionId_ = "";
    /**
     * <code>string default_selected_option_id = 2;</code>
     * @return The defaultSelectedOptionId.
     */
    public String getDefaultSelectedOptionId() {
      Object ref = defaultSelectedOptionId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        defaultSelectedOptionId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string default_selected_option_id = 2;</code>
     * @return The bytes for defaultSelectedOptionId.
     */
    public com.google.protobuf.ByteString
        getDefaultSelectedOptionIdBytes() {
      Object ref = defaultSelectedOptionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        defaultSelectedOptionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string default_selected_option_id = 2;</code>
     * @param value The defaultSelectedOptionId to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultSelectedOptionId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      defaultSelectedOptionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string default_selected_option_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefaultSelectedOptionId() {
      
      defaultSelectedOptionId_ = getDefaultInstance().getDefaultSelectedOptionId();
      onChanged();
      return this;
    }
    /**
     * <code>string default_selected_option_id = 2;</code>
     * @param value The bytes for defaultSelectedOptionId to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultSelectedOptionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      defaultSelectedOptionId_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.ShippingOptionParameters)
  }

  // @@protoc_insertion_point(class_scope:pb.ShippingOptionParameters)
  private static final ShippingOptionParameters DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ShippingOptionParameters();
  }

  public static ShippingOptionParameters getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShippingOptionParameters>
      PARSER = new com.google.protobuf.AbstractParser<ShippingOptionParameters>() {
    @Override
    public ShippingOptionParameters parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShippingOptionParameters(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShippingOptionParameters> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ShippingOptionParameters> getParserForType() {
    return PARSER;
  }

  @Override
  public ShippingOptionParameters getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

