// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/apis/mobile.model.proto

package ru.pnhub.widgetsdk.model;

/**
 * Protobuf type {@code pb.TransactionInfo}
 */
public final class TransactionInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.TransactionInfo)
    TransactionInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionInfo.newBuilder() to construct.
  private TransactionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionInfo() {
    transactionId_ = "";
    currencyCode_ = "";
    countryCode_ = "";
    totalPrice_ = "";
    totalPriceLabel_ = "";
    totalPriceStatus_ = "";
    transactionNote_ = "";
    checkoutOption_ = "";
    displayItems_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransactionInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            transactionId_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            currencyCode_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            countryCode_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            totalPrice_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            totalPriceLabel_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            totalPriceStatus_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            transactionNote_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            checkoutOption_ = s;
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              displayItems_ = new java.util.ArrayList<DisplayItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            displayItems_.add(
                input.readMessage(DisplayItem.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        displayItems_ = java.util.Collections.unmodifiableList(displayItems_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MobileModel.internal_static_pb_TransactionInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MobileModel.internal_static_pb_TransactionInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TransactionInfo.class, Builder.class);
  }

  public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
  private volatile Object transactionId_;
  /**
   * <code>string transaction_id = 1;</code>
   * @return The transactionId.
   */
  @Override
  public String getTransactionId() {
    Object ref = transactionId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      transactionId_ = s;
      return s;
    }
  }
  /**
   * <code>string transaction_id = 1;</code>
   * @return The bytes for transactionId.
   */
  @Override
  public com.google.protobuf.ByteString
      getTransactionIdBytes() {
    Object ref = transactionId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      transactionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENCY_CODE_FIELD_NUMBER = 2;
  private volatile Object currencyCode_;
  /**
   * <code>string currency_code = 2;</code>
   * @return The currencyCode.
   */
  @Override
  public String getCurrencyCode() {
    Object ref = currencyCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      currencyCode_ = s;
      return s;
    }
  }
  /**
   * <code>string currency_code = 2;</code>
   * @return The bytes for currencyCode.
   */
  @Override
  public com.google.protobuf.ByteString
      getCurrencyCodeBytes() {
    Object ref = currencyCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      currencyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTRY_CODE_FIELD_NUMBER = 3;
  private volatile Object countryCode_;
  /**
   * <code>string country_code = 3;</code>
   * @return The countryCode.
   */
  @Override
  public String getCountryCode() {
    Object ref = countryCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      countryCode_ = s;
      return s;
    }
  }
  /**
   * <code>string country_code = 3;</code>
   * @return The bytes for countryCode.
   */
  @Override
  public com.google.protobuf.ByteString
      getCountryCodeBytes() {
    Object ref = countryCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      countryCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_PRICE_FIELD_NUMBER = 4;
  private volatile Object totalPrice_;
  /**
   * <code>string total_price = 4;</code>
   * @return The totalPrice.
   */
  @Override
  public String getTotalPrice() {
    Object ref = totalPrice_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      totalPrice_ = s;
      return s;
    }
  }
  /**
   * <code>string total_price = 4;</code>
   * @return The bytes for totalPrice.
   */
  @Override
  public com.google.protobuf.ByteString
      getTotalPriceBytes() {
    Object ref = totalPrice_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      totalPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_PRICE_LABEL_FIELD_NUMBER = 5;
  private volatile Object totalPriceLabel_;
  /**
   * <code>string total_price_label = 5;</code>
   * @return The totalPriceLabel.
   */
  @Override
  public String getTotalPriceLabel() {
    Object ref = totalPriceLabel_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      totalPriceLabel_ = s;
      return s;
    }
  }
  /**
   * <code>string total_price_label = 5;</code>
   * @return The bytes for totalPriceLabel.
   */
  @Override
  public com.google.protobuf.ByteString
      getTotalPriceLabelBytes() {
    Object ref = totalPriceLabel_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      totalPriceLabel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_PRICE_STATUS_FIELD_NUMBER = 6;
  private volatile Object totalPriceStatus_;
  /**
   * <code>string total_price_status = 6;</code>
   * @return The totalPriceStatus.
   */
  @Override
  public String getTotalPriceStatus() {
    Object ref = totalPriceStatus_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      totalPriceStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string total_price_status = 6;</code>
   * @return The bytes for totalPriceStatus.
   */
  @Override
  public com.google.protobuf.ByteString
      getTotalPriceStatusBytes() {
    Object ref = totalPriceStatus_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      totalPriceStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTION_NOTE_FIELD_NUMBER = 7;
  private volatile Object transactionNote_;
  /**
   * <code>string transaction_note = 7;</code>
   * @return The transactionNote.
   */
  @Override
  public String getTransactionNote() {
    Object ref = transactionNote_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      transactionNote_ = s;
      return s;
    }
  }
  /**
   * <code>string transaction_note = 7;</code>
   * @return The bytes for transactionNote.
   */
  @Override
  public com.google.protobuf.ByteString
      getTransactionNoteBytes() {
    Object ref = transactionNote_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      transactionNote_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHECKOUT_OPTION_FIELD_NUMBER = 8;
  private volatile Object checkoutOption_;
  /**
   * <code>string checkout_option = 8;</code>
   * @return The checkoutOption.
   */
  @Override
  public String getCheckoutOption() {
    Object ref = checkoutOption_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      checkoutOption_ = s;
      return s;
    }
  }
  /**
   * <code>string checkout_option = 8;</code>
   * @return The bytes for checkoutOption.
   */
  @Override
  public com.google.protobuf.ByteString
      getCheckoutOptionBytes() {
    Object ref = checkoutOption_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      checkoutOption_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAY_ITEMS_FIELD_NUMBER = 9;
  private java.util.List<DisplayItem> displayItems_;
  /**
   * <code>repeated .pb.DisplayItem display_items = 9;</code>
   */
  @Override
  public java.util.List<DisplayItem> getDisplayItemsList() {
    return displayItems_;
  }
  /**
   * <code>repeated .pb.DisplayItem display_items = 9;</code>
   */
  @Override
  public java.util.List<? extends DisplayItemOrBuilder>
      getDisplayItemsOrBuilderList() {
    return displayItems_;
  }
  /**
   * <code>repeated .pb.DisplayItem display_items = 9;</code>
   */
  @Override
  public int getDisplayItemsCount() {
    return displayItems_.size();
  }
  /**
   * <code>repeated .pb.DisplayItem display_items = 9;</code>
   */
  @Override
  public DisplayItem getDisplayItems(int index) {
    return displayItems_.get(index);
  }
  /**
   * <code>repeated .pb.DisplayItem display_items = 9;</code>
   */
  @Override
  public DisplayItemOrBuilder getDisplayItemsOrBuilder(
      int index) {
    return displayItems_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTransactionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transactionId_);
    }
    if (!getCurrencyCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currencyCode_);
    }
    if (!getCountryCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, countryCode_);
    }
    if (!getTotalPriceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, totalPrice_);
    }
    if (!getTotalPriceLabelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, totalPriceLabel_);
    }
    if (!getTotalPriceStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, totalPriceStatus_);
    }
    if (!getTransactionNoteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, transactionNote_);
    }
    if (!getCheckoutOptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, checkoutOption_);
    }
    for (int i = 0; i < displayItems_.size(); i++) {
      output.writeMessage(9, displayItems_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTransactionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transactionId_);
    }
    if (!getCurrencyCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currencyCode_);
    }
    if (!getCountryCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, countryCode_);
    }
    if (!getTotalPriceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, totalPrice_);
    }
    if (!getTotalPriceLabelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, totalPriceLabel_);
    }
    if (!getTotalPriceStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, totalPriceStatus_);
    }
    if (!getTransactionNoteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, transactionNote_);
    }
    if (!getCheckoutOptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, checkoutOption_);
    }
    for (int i = 0; i < displayItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, displayItems_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TransactionInfo)) {
      return super.equals(obj);
    }
    TransactionInfo other = (TransactionInfo) obj;

    if (!getTransactionId()
        .equals(other.getTransactionId())) return false;
    if (!getCurrencyCode()
        .equals(other.getCurrencyCode())) return false;
    if (!getCountryCode()
        .equals(other.getCountryCode())) return false;
    if (!getTotalPrice()
        .equals(other.getTotalPrice())) return false;
    if (!getTotalPriceLabel()
        .equals(other.getTotalPriceLabel())) return false;
    if (!getTotalPriceStatus()
        .equals(other.getTotalPriceStatus())) return false;
    if (!getTransactionNote()
        .equals(other.getTransactionNote())) return false;
    if (!getCheckoutOption()
        .equals(other.getCheckoutOption())) return false;
    if (!getDisplayItemsList()
        .equals(other.getDisplayItemsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionId().hashCode();
    hash = (37 * hash) + CURRENCY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrencyCode().hashCode();
    hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCountryCode().hashCode();
    hash = (37 * hash) + TOTAL_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getTotalPrice().hashCode();
    hash = (37 * hash) + TOTAL_PRICE_LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getTotalPriceLabel().hashCode();
    hash = (37 * hash) + TOTAL_PRICE_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalPriceStatus().hashCode();
    hash = (37 * hash) + TRANSACTION_NOTE_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionNote().hashCode();
    hash = (37 * hash) + CHECKOUT_OPTION_FIELD_NUMBER;
    hash = (53 * hash) + getCheckoutOption().hashCode();
    if (getDisplayItemsCount() > 0) {
      hash = (37 * hash) + DISPLAY_ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getDisplayItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TransactionInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TransactionInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TransactionInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TransactionInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TransactionInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TransactionInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TransactionInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TransactionInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TransactionInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TransactionInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TransactionInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TransactionInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TransactionInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.TransactionInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.TransactionInfo)
      TransactionInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MobileModel.internal_static_pb_TransactionInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MobileModel.internal_static_pb_TransactionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransactionInfo.class, Builder.class);
    }

    // Construct using ru.pnhub.widgetsdk.model.TransactionInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDisplayItemsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      transactionId_ = "";

      currencyCode_ = "";

      countryCode_ = "";

      totalPrice_ = "";

      totalPriceLabel_ = "";

      totalPriceStatus_ = "";

      transactionNote_ = "";

      checkoutOption_ = "";

      if (displayItemsBuilder_ == null) {
        displayItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        displayItemsBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MobileModel.internal_static_pb_TransactionInfo_descriptor;
    }

    @Override
    public TransactionInfo getDefaultInstanceForType() {
      return TransactionInfo.getDefaultInstance();
    }

    @Override
    public TransactionInfo build() {
      TransactionInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TransactionInfo buildPartial() {
      TransactionInfo result = new TransactionInfo(this);
      int from_bitField0_ = bitField0_;
      result.transactionId_ = transactionId_;
      result.currencyCode_ = currencyCode_;
      result.countryCode_ = countryCode_;
      result.totalPrice_ = totalPrice_;
      result.totalPriceLabel_ = totalPriceLabel_;
      result.totalPriceStatus_ = totalPriceStatus_;
      result.transactionNote_ = transactionNote_;
      result.checkoutOption_ = checkoutOption_;
      if (displayItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          displayItems_ = java.util.Collections.unmodifiableList(displayItems_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.displayItems_ = displayItems_;
      } else {
        result.displayItems_ = displayItemsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TransactionInfo) {
        return mergeFrom((TransactionInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TransactionInfo other) {
      if (other == TransactionInfo.getDefaultInstance()) return this;
      if (!other.getTransactionId().isEmpty()) {
        transactionId_ = other.transactionId_;
        onChanged();
      }
      if (!other.getCurrencyCode().isEmpty()) {
        currencyCode_ = other.currencyCode_;
        onChanged();
      }
      if (!other.getCountryCode().isEmpty()) {
        countryCode_ = other.countryCode_;
        onChanged();
      }
      if (!other.getTotalPrice().isEmpty()) {
        totalPrice_ = other.totalPrice_;
        onChanged();
      }
      if (!other.getTotalPriceLabel().isEmpty()) {
        totalPriceLabel_ = other.totalPriceLabel_;
        onChanged();
      }
      if (!other.getTotalPriceStatus().isEmpty()) {
        totalPriceStatus_ = other.totalPriceStatus_;
        onChanged();
      }
      if (!other.getTransactionNote().isEmpty()) {
        transactionNote_ = other.transactionNote_;
        onChanged();
      }
      if (!other.getCheckoutOption().isEmpty()) {
        checkoutOption_ = other.checkoutOption_;
        onChanged();
      }
      if (displayItemsBuilder_ == null) {
        if (!other.displayItems_.isEmpty()) {
          if (displayItems_.isEmpty()) {
            displayItems_ = other.displayItems_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDisplayItemsIsMutable();
            displayItems_.addAll(other.displayItems_);
          }
          onChanged();
        }
      } else {
        if (!other.displayItems_.isEmpty()) {
          if (displayItemsBuilder_.isEmpty()) {
            displayItemsBuilder_.dispose();
            displayItemsBuilder_ = null;
            displayItems_ = other.displayItems_;
            bitField0_ = (bitField0_ & ~0x00000001);
            displayItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDisplayItemsFieldBuilder() : null;
          } else {
            displayItemsBuilder_.addAllMessages(other.displayItems_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TransactionInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TransactionInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object transactionId_ = "";
    /**
     * <code>string transaction_id = 1;</code>
     * @return The transactionId.
     */
    public String getTransactionId() {
      Object ref = transactionId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @return The bytes for transactionId.
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      Object ref = transactionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @param value The transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionId() {
      
      transactionId_ = getDefaultInstance().getTransactionId();
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @param value The bytes for transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transactionId_ = value;
      onChanged();
      return this;
    }

    private Object currencyCode_ = "";
    /**
     * <code>string currency_code = 2;</code>
     * @return The currencyCode.
     */
    public String getCurrencyCode() {
      Object ref = currencyCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        currencyCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string currency_code = 2;</code>
     * @return The bytes for currencyCode.
     */
    public com.google.protobuf.ByteString
        getCurrencyCodeBytes() {
      Object ref = currencyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        currencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currency_code = 2;</code>
     * @param value The currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currencyCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string currency_code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrencyCode() {
      
      currencyCode_ = getDefaultInstance().getCurrencyCode();
      onChanged();
      return this;
    }
    /**
     * <code>string currency_code = 2;</code>
     * @param value The bytes for currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currencyCode_ = value;
      onChanged();
      return this;
    }

    private Object countryCode_ = "";
    /**
     * <code>string country_code = 3;</code>
     * @return The countryCode.
     */
    public String getCountryCode() {
      Object ref = countryCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string country_code = 3;</code>
     * @return The bytes for countryCode.
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      Object ref = countryCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string country_code = 3;</code>
     * @param value The countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      countryCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountryCode() {
      
      countryCode_ = getDefaultInstance().getCountryCode();
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 3;</code>
     * @param value The bytes for countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      countryCode_ = value;
      onChanged();
      return this;
    }

    private Object totalPrice_ = "";
    /**
     * <code>string total_price = 4;</code>
     * @return The totalPrice.
     */
    public String getTotalPrice() {
      Object ref = totalPrice_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        totalPrice_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string total_price = 4;</code>
     * @return The bytes for totalPrice.
     */
    public com.google.protobuf.ByteString
        getTotalPriceBytes() {
      Object ref = totalPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        totalPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string total_price = 4;</code>
     * @param value The totalPrice to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPrice(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totalPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string total_price = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPrice() {
      
      totalPrice_ = getDefaultInstance().getTotalPrice();
      onChanged();
      return this;
    }
    /**
     * <code>string total_price = 4;</code>
     * @param value The bytes for totalPrice to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totalPrice_ = value;
      onChanged();
      return this;
    }

    private Object totalPriceLabel_ = "";
    /**
     * <code>string total_price_label = 5;</code>
     * @return The totalPriceLabel.
     */
    public String getTotalPriceLabel() {
      Object ref = totalPriceLabel_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        totalPriceLabel_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string total_price_label = 5;</code>
     * @return The bytes for totalPriceLabel.
     */
    public com.google.protobuf.ByteString
        getTotalPriceLabelBytes() {
      Object ref = totalPriceLabel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        totalPriceLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string total_price_label = 5;</code>
     * @param value The totalPriceLabel to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPriceLabel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totalPriceLabel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string total_price_label = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPriceLabel() {
      
      totalPriceLabel_ = getDefaultInstance().getTotalPriceLabel();
      onChanged();
      return this;
    }
    /**
     * <code>string total_price_label = 5;</code>
     * @param value The bytes for totalPriceLabel to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPriceLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totalPriceLabel_ = value;
      onChanged();
      return this;
    }

    private Object totalPriceStatus_ = "";
    /**
     * <code>string total_price_status = 6;</code>
     * @return The totalPriceStatus.
     */
    public String getTotalPriceStatus() {
      Object ref = totalPriceStatus_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        totalPriceStatus_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string total_price_status = 6;</code>
     * @return The bytes for totalPriceStatus.
     */
    public com.google.protobuf.ByteString
        getTotalPriceStatusBytes() {
      Object ref = totalPriceStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        totalPriceStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string total_price_status = 6;</code>
     * @param value The totalPriceStatus to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPriceStatus(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totalPriceStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string total_price_status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPriceStatus() {
      
      totalPriceStatus_ = getDefaultInstance().getTotalPriceStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string total_price_status = 6;</code>
     * @param value The bytes for totalPriceStatus to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPriceStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totalPriceStatus_ = value;
      onChanged();
      return this;
    }

    private Object transactionNote_ = "";
    /**
     * <code>string transaction_note = 7;</code>
     * @return The transactionNote.
     */
    public String getTransactionNote() {
      Object ref = transactionNote_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transactionNote_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string transaction_note = 7;</code>
     * @return The bytes for transactionNote.
     */
    public com.google.protobuf.ByteString
        getTransactionNoteBytes() {
      Object ref = transactionNote_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        transactionNote_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transaction_note = 7;</code>
     * @param value The transactionNote to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionNote(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionNote_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_note = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionNote() {
      
      transactionNote_ = getDefaultInstance().getTransactionNote();
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_note = 7;</code>
     * @param value The bytes for transactionNote to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionNoteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transactionNote_ = value;
      onChanged();
      return this;
    }

    private Object checkoutOption_ = "";
    /**
     * <code>string checkout_option = 8;</code>
     * @return The checkoutOption.
     */
    public String getCheckoutOption() {
      Object ref = checkoutOption_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        checkoutOption_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string checkout_option = 8;</code>
     * @return The bytes for checkoutOption.
     */
    public com.google.protobuf.ByteString
        getCheckoutOptionBytes() {
      Object ref = checkoutOption_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        checkoutOption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string checkout_option = 8;</code>
     * @param value The checkoutOption to set.
     * @return This builder for chaining.
     */
    public Builder setCheckoutOption(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      checkoutOption_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string checkout_option = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCheckoutOption() {
      
      checkoutOption_ = getDefaultInstance().getCheckoutOption();
      onChanged();
      return this;
    }
    /**
     * <code>string checkout_option = 8;</code>
     * @param value The bytes for checkoutOption to set.
     * @return This builder for chaining.
     */
    public Builder setCheckoutOptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      checkoutOption_ = value;
      onChanged();
      return this;
    }

    private java.util.List<DisplayItem> displayItems_ =
      java.util.Collections.emptyList();
    private void ensureDisplayItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        displayItems_ = new java.util.ArrayList<DisplayItem>(displayItems_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        DisplayItem, DisplayItem.Builder, DisplayItemOrBuilder> displayItemsBuilder_;

    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public java.util.List<DisplayItem> getDisplayItemsList() {
      if (displayItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(displayItems_);
      } else {
        return displayItemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public int getDisplayItemsCount() {
      if (displayItemsBuilder_ == null) {
        return displayItems_.size();
      } else {
        return displayItemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public DisplayItem getDisplayItems(int index) {
      if (displayItemsBuilder_ == null) {
        return displayItems_.get(index);
      } else {
        return displayItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public Builder setDisplayItems(
        int index, DisplayItem value) {
      if (displayItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDisplayItemsIsMutable();
        displayItems_.set(index, value);
        onChanged();
      } else {
        displayItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public Builder setDisplayItems(
        int index, DisplayItem.Builder builderForValue) {
      if (displayItemsBuilder_ == null) {
        ensureDisplayItemsIsMutable();
        displayItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        displayItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public Builder addDisplayItems(DisplayItem value) {
      if (displayItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDisplayItemsIsMutable();
        displayItems_.add(value);
        onChanged();
      } else {
        displayItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public Builder addDisplayItems(
        int index, DisplayItem value) {
      if (displayItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDisplayItemsIsMutable();
        displayItems_.add(index, value);
        onChanged();
      } else {
        displayItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public Builder addDisplayItems(
        DisplayItem.Builder builderForValue) {
      if (displayItemsBuilder_ == null) {
        ensureDisplayItemsIsMutable();
        displayItems_.add(builderForValue.build());
        onChanged();
      } else {
        displayItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public Builder addDisplayItems(
        int index, DisplayItem.Builder builderForValue) {
      if (displayItemsBuilder_ == null) {
        ensureDisplayItemsIsMutable();
        displayItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        displayItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public Builder addAllDisplayItems(
        Iterable<? extends DisplayItem> values) {
      if (displayItemsBuilder_ == null) {
        ensureDisplayItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, displayItems_);
        onChanged();
      } else {
        displayItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public Builder clearDisplayItems() {
      if (displayItemsBuilder_ == null) {
        displayItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        displayItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public Builder removeDisplayItems(int index) {
      if (displayItemsBuilder_ == null) {
        ensureDisplayItemsIsMutable();
        displayItems_.remove(index);
        onChanged();
      } else {
        displayItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public DisplayItem.Builder getDisplayItemsBuilder(
        int index) {
      return getDisplayItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public DisplayItemOrBuilder getDisplayItemsOrBuilder(
        int index) {
      if (displayItemsBuilder_ == null) {
        return displayItems_.get(index);  } else {
        return displayItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public java.util.List<? extends DisplayItemOrBuilder>
         getDisplayItemsOrBuilderList() {
      if (displayItemsBuilder_ != null) {
        return displayItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(displayItems_);
      }
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public DisplayItem.Builder addDisplayItemsBuilder() {
      return getDisplayItemsFieldBuilder().addBuilder(
          DisplayItem.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public DisplayItem.Builder addDisplayItemsBuilder(
        int index) {
      return getDisplayItemsFieldBuilder().addBuilder(
          index, DisplayItem.getDefaultInstance());
    }
    /**
     * <code>repeated .pb.DisplayItem display_items = 9;</code>
     */
    public java.util.List<DisplayItem.Builder>
         getDisplayItemsBuilderList() {
      return getDisplayItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        DisplayItem, DisplayItem.Builder, DisplayItemOrBuilder>
        getDisplayItemsFieldBuilder() {
      if (displayItemsBuilder_ == null) {
        displayItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            DisplayItem, DisplayItem.Builder, DisplayItemOrBuilder>(
                displayItems_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        displayItems_ = null;
      }
      return displayItemsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.TransactionInfo)
  }

  // @@protoc_insertion_point(class_scope:pb.TransactionInfo)
  private static final TransactionInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TransactionInfo();
  }

  public static TransactionInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionInfo>
      PARSER = new com.google.protobuf.AbstractParser<TransactionInfo>() {
    @Override
    public TransactionInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TransactionInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public TransactionInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

